### ISSUE TITLE
ArrayIndexOutOfBoundsException on key change for Oberthur COSMO 8.1 cards

### ISSUE THREAD

**Issue by gmkbenjamin** [martinpaljak/GlobalPlatformPro#114]
λ gp -r "Broadcom Corp Contacted SmartCard 0" -kdf3 -key 808CD8F1E4850B13DB50DCAA102C85DC6D877437C0D97A0C537196577D508852 -v -d -lock 101112131415161718191A1B1C1D1E1F202122232425262728292A2B2C2D2E2F
GlobalPlatformPro v0.3.10rc7-7-g6ed0550
Running on Windows 10 10.0 amd64, Java 1.8.0_161 by Oracle Corporation
# Detected readers from JNA2PCSC
[*] Broadcom Corp Contacted SmartCard 0
[ ] Broadcom Corp Contactless SmartCard 0
[ ] BROADCOM NFC Smartcard Reader 0
[*] Microsoft Virtual Smart Card 0
SCardConnect("Broadcom Corp Contacted SmartCard 0", T=*) -> T=1, 3BD6970081B1FE451F878031C152211A4B
SCardBeginTransaction("Broadcom Corp Contacted SmartCard 0")
Reader: Broadcom Corp Contacted SmartCard 0
ATR: 3BD6970081B1FE451F878031C152211A4B
More information about your card:
    http://smartcard-atr.appspot.com/parse?ATR=3BD6970081B1FE451F878031C152211A4B

A>> T=1 (4+0000) 00A40400 00
A<< (0066+2) (31ms) 6F408407A0000001510000A535732F06072A864886FC6B01600C060A2A864886FC6B02020201630906072A864886FC6B03640B06092A864886FC6B0403709F6501FF 9000
[DEBUG] GlobalPlatform - Auto-detected ISD: A0000001510000
A>> T=1 (4+0008) 80500000 08 D1C33846CD899B02 00
A<< (0032+2) (62ms) 149480576000078C0100010370E7881AD1FDAF0067A20BC81393BE45A3000015 9000
[DEBUG] GlobalPlatform - Host challenge: D1C33846CD899B02
[DEBUG] GlobalPlatform - Card challenge: E7881AD1FDAF0067
[DEBUG] GlobalPlatform - Card reports SCP03 i=70 with key version 1 (0x01)
[DEBUG] GlobalPlatform - SCP03 i=112
[DEBUG] GlobalPlatform - Will do SCP03 (3)
[DEBUG] PlaintextKeys - Card keys: {ENC=type=RAW bytes=808CD8F1E4850B13DB50DCAA102C85DC6D877437C0D97A0C537196577D508852, DEK=type=RAW bytes=808CD8F1E4850B13DB50DCAA102C85DC6D877437C0D97A0C537196577D508852, MAC=type=RAW bytes=808CD8F1E4850B13DB50DCAA102C85DC6D877437C0D97A0C537196577D508852}
[DEBUG] PlaintextKeys - Derived per-card keys: {ENC=type=AES bytes=D6CAABD673C7248CD7A9AC45914A9FC1B795C9D1954EF649E30F0D683F0368C6 kcv=48DA02, DEK=type=AES bytes=A82C099ED6AF294DF1CA717E0A2CEE1A3415C4AE6387BF2FCC389C8B672FF643 kcv=EC37A1, MAC=type=AES bytes=C9F96A6BA1ED6DE51E0680D3D25C1E05350DC1522B6737EEA886929581D4D2B0 kcv=BD7B5C}
[DEBUG] PlaintextKeys - Session keys: {ENC=type=AES bytes=DF891319102A9BE310C4FD16C70E24FACA8D473A0F9CD84E7209966F0E2E4F0E kcv=9D18D7, DEK=type=AES bytes=A82C099ED6AF294DF1CA717E0A2CEE1A3415C4AE6387BF2FCC389C8B672FF643 kcv=EC37A1, MAC=type=AES bytes=E178FD9246D244DF3087FEE46B73657CCA4D60FA6CBBB71789BCB60600723DDC kcv=D123A3}
[DEBUG] GlobalPlatform - Verified card cryptogram: A20BC81393BE45A3
[DEBUG] GlobalPlatform - Calculated host cryptogram: C88F45FF3183D009
A>> T=1 (4+0016) 84820100 10 C88F45FF3183D0094AD87CA757B9D1EA
A<< (0000+2) (31ms) 9000
A>> T=1 (4+0008) 84CA00E0 08 4FDB98DED1508A2E
A<< (0000+2) (94ms) 9000
[DEBUG] GlobalPlatform - PUT KEY version 1
A>> T=1 (4+0008) 84CA00E0 08 7FC7F7DAB240A9FF
A<< (0000+2) (94ms) 9000
[WARN] GlobalPlatform - No key template on card but trying to replace. Implying add
SCardEndTransaction(Broadcom Corp Contacted SmartCard 0)
SCardDisconnect("Broadcom Corp Contacted SmartCard 0", true)
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException
        at java.lang.System.arraycopy(Native Method)
        at pro.javacard.gp.GPCrypto.scp03_encrypt_key(GPCrypto.java:229)
        at pro.javacard.gp.GlobalPlatform.encodeKey(GlobalPlatform.java:825)
        at pro.javacard.gp.GlobalPlatform.putKeys(GlobalPlatform.java:904)
        at pro.javacard.gp.GPTool.main(GPTool.java:827)

**Comment by martinpaljak** [comment]
Same here - there was a blatant bug and missing code for SCP03, added in rc8. Please re-try with that.

**Comment by gmkbenjamin** [comment]
:( same

**Comment by martinpaljak** [comment]
Do you have the relevant log please? A card in SECURED state should have a valid key template for the ISD?

**Comment by gmkbenjamin** [comment]
On change key:
λ gp -r "Gemplus USB Smart Card Reader 0" -kdf3 -key 808CD8F1E4850B13DB50DCAA102C85DC6D877437C0D97A0C537196577D508852 -v -d -lock 101112131415161718191A1B1C1D1E1F202122232425262728292A2B2C2D2E2F
GlobalPlatformPro v0.3.10rc8-0-gf1dcf34
Running on Windows 10 10.0 amd64, Java 1.8.0_161 by Oracle Corporation
# Detected readers from JNA2PCSC
[*] Broadcom Corp Contacted SmartCard 0
[ ] Broadcom Corp Contactless SmartCard 0
[ ] BROADCOM NFC Smartcard Reader 0
[*] Gemplus USB Smart Card Reader 0
[*] Microsoft Virtual Smart Card 0
SCardConnect("Gemplus USB Smart Card Reader 0", T=*) -> T=1, 3BD6970081B1FE451F878031C152211A4B
SCardBeginTransaction("Gemplus USB Smart Card Reader 0")
Reader: Gemplus USB Smart Card Reader 0
ATR: 3BD6970081B1FE451F878031C152211A4B
More information about your card:
    http://smartcard-atr.appspot.com/parse?ATR=3BD6970081B1FE451F878031C152211A4B

A>> T=1 (4+0000) 00A40400 00
A<< (0066+2) (32ms) 6F408407A0000001510000A535732F06072A864886FC6B01600C060A2A864886FC6B02020201630906072A864886FC6B03640B06092A864886FC6B0403709F6501FF 9000
[DEBUG] GlobalPlatform - Auto-detected ISD: A0000001510000
A>> T=1 (4+0008) 80500000 08 4D5FED791C9C8A50 00
A<< (0032+2) (63ms) 149480576000078C0100010370A77132FC98021BA9D44F6712C878211800001E 9000
[DEBUG] GlobalPlatform - Host challenge: 4D5FED791C9C8A50
[DEBUG] GlobalPlatform - Card challenge: A77132FC98021BA9
[DEBUG] GlobalPlatform - Card reports SCP03 i=70 with key version 1 (0x01)
[DEBUG] GlobalPlatform - Will do SCP03 (3)
[DEBUG] PlaintextKeys - Card keys: {ENC=type=RAW bytes=808CD8F1E4850B13DB50DCAA102C85DC6D877437C0D97A0C537196577D508852, DEK=type=RAW bytes=808CD8F1E4850B13DB50DCAA102C85DC6D877437C0D97A0C537196577D508852, MAC=type=RAW bytes=808CD8F1E4850B13DB50DCAA102C85DC6D877437C0D97A0C537196577D508852}
[DEBUG] PlaintextKeys - Derived per-card keys: {ENC=type=AES bytes=D6CAABD673C7248CD7A9AC45914A9FC1B795C9D1954EF649E30F0D683F0368C6 kcv=48DA02, DEK=type=AES bytes=A82C099ED6AF294DF1CA717E0A2CEE1A3415C4AE6387BF2FCC389C8B672FF643 kcv=EC37A1, MAC=type=AES bytes=C9F96A6BA1ED6DE51E0680D3D25C1E05350DC1522B6737EEA886929581D4D2B0 kcv=BD7B5C}
[DEBUG] PlaintextKeys - Session keys: {ENC=type=AES bytes=03A930ADB7B208102F9710A1070CA5C9E9CB86260E7E9968DC3B3F375EB94556 kcv=91811A, DEK=type=AES bytes=A82C099ED6AF294DF1CA717E0A2CEE1A3415C4AE6387BF2FCC389C8B672FF643 kcv=EC37A1, MAC=type=AES bytes=CB49248BD6A0334DE895D8370799BFABFA4905CAEC2C0AF02726A429A5E427E2 kcv=6BD01D, RMAC=type=AES bytes=A1F46C4C17EBA0EA5A4C329950302B4DBE458DE095298E508ABAA48BC10919C0 kcv=03C382}
[DEBUG] GlobalPlatform - Verified card cryptogram: D44F6712C8782118
[DEBUG] GlobalPlatform - Calculated host cryptogram: D5A20933F922EEB1
A>> T=1 (4+0016) 84820100 10 D5A20933F922EEB10B9E3846E589D3AC
A<< (0000+2) (31ms) 9000
A>> T=1 (4+0008) 84CA00E0 08 246790AE0601762C 00
A<< (0020+2) (94ms) E012C00401018820C00402018820C00403018820 9000
[DEBUG] GlobalPlatform - PUT KEY version 1
A>> T=1 (4+0008) 84CA00E0 08 0E453E8607B1FC42 00
A<< (0020+2) (94ms) E012C00401018820C00402018820C00403018820 9000
SCardEndTransaction(Gemplus USB Smart Card Reader 0)
SCardDisconnect("Gemplus USB Smart Card Reader 0", true)
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException
        at java.lang.System.arraycopy(Native Method)
        at pro.javacard.gp.GPCrypto.scp03_encrypt_key(GPCrypto.java:242)
        at pro.javacard.gp.GlobalPlatform.encodeKey(GlobalPlatform.java:824)
        at pro.javacard.gp.GlobalPlatform.putKeys(GlobalPlatform.java:903)
        at pro.javacard.gp.GPTool.main(GPTool.java:829)


info:
GlobalPlatformPro v0.3.10rc8-0-gf1dcf34
Running on Windows 10 10.0 amd64, Java 1.8.0_161 by Oracle Corporation
# Detected readers from JNA2PCSC
[*] Broadcom Corp Contacted SmartCard 0
[ ] Broadcom Corp Contactless SmartCard 0
[ ] BROADCOM NFC Smartcard Reader 0
[*] Gemplus USB Smart Card Reader 0
[*] Microsoft Virtual Smart Card 0
SCardConnect("Gemplus USB Smart Card Reader 0", T=*) -> T=1, 3BD6970081B1FE451F878031C152211A4B
SCardBeginTransaction("Gemplus USB Smart Card Reader 0")
Reader: Gemplus USB Smart Card Reader 0
ATR: 3BD6970081B1FE451F878031C152211A4B
More information about your card:
    http://smartcard-atr.appspot.com/parse?ATR=3BD6970081B1FE451F878031C152211A4B

A>> T=1 (4+0000) 00A40400 00
A<< (0066+2) (31ms) 6F408407A0000001510000A535732F06072A864886FC6B01600C060A2A864886FC6B02020201630906072A864886FC6B03640B06092A864886FC6B0403709F6501FF 9000
[DEBUG] GlobalPlatform - Auto-detected ISD: A0000001510000
A>> T=1 (4+0000) 80CA9F7F 00
A<< (0045+2) (15ms) 9F7F2A47906B4882316083009A80576000078C1494114280571143805711448057130013060000000000000000 9000
CPLC: ICFabricator=4790
      ICType=6B48
      OperatingSystemID=8231
      OperatingSystemReleaseDate=6083 (2016-03-23)
      OperatingSystemReleaseLevel=009A
      ICFabricationDate=8057 (2018-02-26)
      ICSerialNumber=6000078C
      ICBatchIdentifier=1494
      ICModuleFabricator=1142
      ICModulePackagingDate=8057 (2018-02-26)
      ICCManufacturer=1143
      ICEmbeddingDate=8057 (2018-02-26)
      ICPrePersonalizer=1144
      ICPrePersonalizationEquipmentDate=8057 (2018-02-26)
      ICPrePersonalizationEquipmentID=13001306
      ICPersonalizer=0000
      ICPersonalizationDate=0000 (2010-01-01)
      ICPersonalizationEquipmentID=00000000

***** GET DATA:
A>> T=1 (4+0000) 80CA0042 00
A<< (0000+2) (16ms) 6A88
GET DATA(IIN): not supported: 0x6A88 (Referenced data not found)
A>> T=1 (4+0000) 80CA0045 00
A<< (0000+2) (15ms) 6A88
GET DATA(CIN): not supported: 0x6A88 (Referenced data not found)
A>> T=1 (4+0000) 80CA00C1 00
A<< (0005+2) (19ms) C10300001E 9000
GET DATA(SSC): 00001E
***** CARD DATA
A>> T=1 (4+0000) 80CA0066 00
A<< (0051+2) (17ms) 6631732F06072A864886FC6B01600C060A2A864886FC6B02020201630906072A864886FC6B03640B06092A864886FC6B040370 9000
Tag 6: 1.2.840.114283.1
-> Global Platform card
Tag 60: 1.2.840.114283.2.2.2.1
-> GP Version: 2.2.1
Tag 63: 1.2.840.114283.3
Tag 64: 1.2.840.114283.4.3.112
-> GP SCP03 i=70
***** KEY INFO
A>> T=1 (4+0000) 80CA00E0 00
A<< (0020+2) (94ms) E012C00401018820C00402018820C00403018820 9000
Version:   1 (0x01) ID:   1 (0x01) type: AES  length:  32 (AES-256)
Version:   1 (0x01) ID:   2 (0x02) type: AES  length:  32 (AES-256)
Version:   1 (0x01) ID:   3 (0x03) type: AES  length:  32 (AES-256)
SCardEndTransaction(Gemplus USB Smart Card Reader 0)
SCardDisconnect("Gemplus USB Smart Card Reader 0", true)


-l:
λ gp -r "Gemplus USB Smart Card Reader 0" -kdf3 -key 808CD8F1E4850B13DB50DCAA102C85DC6D877437C0D97A0C537196577D508852 -v -d -l
GlobalPlatformPro v0.3.10rc8-0-gf1dcf34
Running on Windows 10 10.0 amd64, Java 1.8.0_161 by Oracle Corporation
# Detected readers from JNA2PCSC
[*] Broadcom Corp Contacted SmartCard 0
[ ] Broadcom Corp Contactless SmartCard 0
[ ] BROADCOM NFC Smartcard Reader 0
[*] Gemplus USB Smart Card Reader 0
[*] Microsoft Virtual Smart Card 0
SCardConnect("Gemplus USB Smart Card Reader 0", T=*) -> T=1, 3BD6970081B1FE451F878031C152211A4B
SCardBeginTransaction("Gemplus USB Smart Card Reader 0")
Reader: Gemplus USB Smart Card Reader 0
ATR: 3BD6970081B1FE451F878031C152211A4B
More information about your card:
    http://smartcard-atr.appspot.com/parse?ATR=3BD6970081B1FE451F878031C152211A4B

A>> T=1 (4+0000) 00A40400 00
A<< (0066+2) (31ms) 6F408407A0000001510000A535732F06072A864886FC6B01600C060A2A864886FC6B02020201630906072A864886FC6B03640B06092A864886FC6B0403709F6501FF 9000
[DEBUG] GlobalPlatform - Auto-detected ISD: A0000001510000
A>> T=1 (4+0008) 80500000 08 47BBDD7EDEDCF984 00
A<< (0032+2) (62ms) 149480576000078C010001037091EEE7A11FC056ACF08A788607A6D56900001F 9000
[DEBUG] GlobalPlatform - Host challenge: 47BBDD7EDEDCF984
[DEBUG] GlobalPlatform - Card challenge: 91EEE7A11FC056AC
[DEBUG] GlobalPlatform - Card reports SCP03 i=70 with key version 1 (0x01)
[DEBUG] GlobalPlatform - Will do SCP03 (3)
[DEBUG] PlaintextKeys - Card keys: {ENC=type=RAW bytes=808CD8F1E4850B13DB50DCAA102C85DC6D877437C0D97A0C537196577D508852, DEK=type=RAW bytes=808CD8F1E4850B13DB50DCAA102C85DC6D877437C0D97A0C537196577D508852, MAC=type=RAW bytes=808CD8F1E4850B13DB50DCAA102C85DC6D877437C0D97A0C537196577D508852}
[DEBUG] PlaintextKeys - Derived per-card keys: {ENC=type=AES bytes=D6CAABD673C7248CD7A9AC45914A9FC1B795C9D1954EF649E30F0D683F0368C6 kcv=48DA02, DEK=type=AES bytes=A82C099ED6AF294DF1CA717E0A2CEE1A3415C4AE6387BF2FCC389C8B672FF643 kcv=EC37A1, MAC=type=AES bytes=C9F96A6BA1ED6DE51E0680D3D25C1E05350DC1522B6737EEA886929581D4D2B0 kcv=BD7B5C}
[DEBUG] PlaintextKeys - Session keys: {ENC=type=AES bytes=D2C95F56A3CEABDDF5DD0779D6A9FA7900719071CB8DC92933CF8B4B0752A950 kcv=7D833B, DEK=type=AES bytes=A82C099ED6AF294DF1CA717E0A2CEE1A3415C4AE6387BF2FCC389C8B672FF643 kcv=EC37A1, MAC=type=AES bytes=DF0ABD732D5C73124FB41D1835CB749FC1C41D81396BFEC0B410525F3CA46C87 kcv=F699B8, RMAC=type=AES bytes=2683ED201598E75218BC56FBA7E327C2EB5EA542CAF5E1433FB157376FFAAAF1 kcv=3A006A}
[DEBUG] GlobalPlatform - Verified card cryptogram: F08A788607A6D569
[DEBUG] GlobalPlatform - Calculated host cryptogram: 390AA6C92C254A80
A>> T=1 (4+0016) 84820100 10 390AA6C92C254A80D36BF67AD92B8C5E
A<< (0000+2) (31ms) 9000
A>> T=1 (4+0010) 84F28002 0A 4F000589D33CB1ECF99E 00
A<< (0020+2) (148ms) E3124F07A00000015100009F70010FC5039EFE80 9000
A>> T=1 (4+0010) 84F24002 0A 4F00DC2770939D76D38D 00
A<< (0100+2) (453ms) E31B4F10A000000077010000061000FD000000269F70010FC503C18000E31B4F10A000000077010808072000F1000005009F700107C503000000E3164F0BA0000003080000100001009F70010FC503100000E3104F05FFFFFFFFFF9F70010FC503000000 9000
A>> T=1 (4+0010) 84F22002 0A 4F00082E178F89029795 00
A<< (0135+2) (343ms) E30D4F07A00000015153509F700101E3164F10A00000007701080807200000000000039F700101E3164F10A00000007701080807200000000000029F700101E3164F10A00000007701080807200000000000019F700101E3164F10A00000007701080807200000000000059F700101E3164F10A00000007701000006100000000000249F700101 9000
A>> T=1 (4+0010) 84F21002 0A 4F00C335A30CCAF6B2E9 00
A<< (0000+2) (227ms) 6F02
[WARN] GlobalPlatform - GET STATUS failed for 80F21002024F0000 with 0x6F02
ISD: A0000001510000 (SECURED)
     Privs:   SecurityDomain, CardLock, CardTerminate, CardReset, CVMManagement, TrustedPath, AuthorizedManagement, TokenVerification, GlobalDelete, GlobalLock, GlobalRegistry, FinalApplication, ReceiptGeneration

DOM: A000000077010000061000FD00000026 (PERSONALIZED) (|....w..........&|)
     Privs:   SecurityDomain, MandatedDAPVerification, TrustedPath

APP: A000000077010808072000F100000500 (SELECTABLE) (|....w.... ......|)
     Privs:

APP: A000000308000010000100 (SELECTABLE (0xf)) (|...........|)
     Privs:   CardLock

APP: FFFFFFFFFF (SELECTABLE (0xf)) (|.....|)
     Privs:

PKG: A0000001515350 (LOADED) (|....QSP|)

PKG: A0000000770108080720000000000003 (LOADED) (|....w.... ......|)

PKG: A0000000770108080720000000000002 (LOADED) (|....w.... ......|)

PKG: A0000000770108080720000000000001 (LOADED) (|....w.... ......|)

PKG: A0000000770108080720000000000005 (LOADED) (|....w.... ......|)

PKG: A0000000770100000610000000000024 (LOADED) (|....w..........$|)

SCardEndTransaction(Gemplus USB Smart Card Reader 0)
SCardDisconnect("Gemplus USB Smart Card Reader 0", true)

**Comment by martinpaljak** [comment]
OK. This a bug.
