### ISSUE TITLE
testCPLCDateParse fails in CET/CEST timezone after midnight

### ISSUE THREAD

**Issue by tista3** [martinpaljak/GlobalPlatformPro#116]
I run into funny issue. One of the test is failing based on time and timezone set in my Ubuntu. While in CET (GMT+1) I get this failure at 0:00-0:59, while in the CEST, I get it at 0:00-1:59.
Manually changing time outside these intervals is a working workaround.
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running TestSCP03
Master: 8C72C72CF908411653018807950D82FBAD947562F0828A0B10B8B9606ABF3BCD
KDD: D9B1DE5D0362DEDCE4FB
ENC: 9AAC5D0B3601F89438A0D9D0B6B256CFB47E6462DFA5228D3420C4AC7C224781
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.521 sec
Running TestParseTags
Tag 6: 1.2.840.114283.1
-> Global Platform card
Tag 60: 1.2.840.114283.2.2.1.1
-> GP Version: 2.1.1
Tag 63: 1.2.840.114283.3
Tag 64: 1.2.840.114283.4.2.21
-> GP SCP02 i=15
Tag 65: 1.3.656.840.100.2.1.3
Tag 66: 1.3.6.1.4.1.42.2.110.1.2
-> JavaCard v2?
Tag 6: 1.2.840.114283.1
-> Global Platform card
Tag 60: 1.2.840.114283.2.2.2
-> GP Version: 2.2
Tag 63: 1.2.840.114283.3
Tag 64: 1.2.840.114283.4.3.112
-> GP SCP03 i=70
Tag 64: 1.2.840.114283.4.0
-> GP SCP80 i=00
Tag 65: 1.2.840.114283.5.4
Tag 66: 1.3.6.1.4.1.42.2.110.1.3
-> JavaCard v3?
Version:   1 (0x01) ID:   1 (0x01) type: AES  length:  32 (AES-256)
Version:   1 (0x01) ID:   2 (0x02) type: AES  length:  32 (AES-256)
Version:   1 (0x01) ID:   3 (0x03) type: AES  length:  32 (AES-256)
Version: 112 (0x70) ID:   1 (0x01) type: RSA  length: 128 (RSA-1024 public)
Version: 113 (0x71) ID:   1 (0x01) type: DES3 length:  16 
Tests run: 7, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.083 sec <<< FAILURE!
testCPLCDateParse(TestParseTags)  Time elapsed: 0.041 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<2011-07-[29]> but was:<2011-07-[30]>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at TestParseTags.testCPLCDateParse(TestParseTags.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Running TestSEAC
RULE #0 :
       HASH : A90D0190BFC879DBE161A3DF66B6352C68B85C18
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec

Results :

Failed tests:   testCPLCDateParse(TestParseTags): expected:<2011-07-[29]> but was:<2011-07-[30]>

Tests run: 9, Failures: 1, Errors: 0, Skipped: 0
```

**Comment by gmkbenjamin** [comment]
Oh my god, that's what it was. I was wondering why I only saw the issue once and it kind disappeared from the next day.

**Comment by martinpaljak** [comment]
Hmm.. Thanks for the report. A patch would be most welcome :)

**Comment by martinpaljak** [comment]
I can't figure this out. All times should be converted to UTC, exactly for this issue to not happen. Would be cool if somebody pointed to the bug in the code
