### ISSUE TITLE
Locking Card Failed with problem matching keys and versions

### ISSUE THREAD

**Issue by thotheolh** [martinpaljak/GlobalPlatformPro#154]
I am trying to lock a card with 0x60 .. 6F and I am getting a problem locking card due to non-matching keys and versions:

```
>java -jar gp-official-v0_3_10_rc4.jar --lock 606162636465666768696A6B6C6D6E6F --verbose --debug
GlobalPlatformPro v0.3.10rc4-0-gb81610e
Running on Windows 7 6.1 amd64, Java 1.8.0_151 by Oracle Corporation
# Detected readers from JNA2PCSC
[*] XXXXXXXXXX Reader 0
SCardConnect("XXXXXXXXXX Reader 0", T=*) -> T=0, 3B189657694C4C20181024
SCardBeginTransaction("XXXXXXXXXX Reader 0")
Reader: XXXXXXXXXX Reader 0
ATR: 3B189657694C4C20181024
More information about your card:
    http://smartcard-atr.appspot.com/parse?ATR=3B189657694C4C20181024

A>> T=0 (4+0000) 00A40400 00
A<< (0093+2) (129ms) 6F5B8408A000000003000000A54F734906072A864886FC6B01600B06092
A864886FC6B020202630906072A864886FC6B03640B06092A864886FC6B040255650B06092A86488
6FC6B020101660C060A2B060104012A026E01029F6501FF 9000
[DEBUG] GlobalPlatform - Auto-detected ISD: [AID: A000000003000000]
Warning: no keys given, using default test key 404142434445464748494A4B4C4D4E4F
A>> T=0 (4+0008) 80500000 08 AD34599E02D8FAF7 00
A<< (0028+2) (119ms) 0000008C00002B170AC0200203B24028A18D797BC5DFD309EDB24B73 90
00
[DEBUG] GlobalPlatform - Host challenge: AD34599E02D8FAF7
[DEBUG] GlobalPlatform - Card challenge: 03B24028A18D797B
[DEBUG] GlobalPlatform - Card reports SCP02 i=ffffffff keys 0
[DEBUG] GlobalPlatform - Will do SCP02 (8)
[DEBUG] PlaintextKeys - Card keys: {DEK=version=0 id=0 type=RAW bytes=4041424344
45464748494A4B4C4D4E4F, ENC=version=0 id=0 type=RAW bytes=404142434445464748494A
4B4C4D4E4F, MAC=version=0 id=0 type=RAW bytes=404142434445464748494A4B4C4D4E4F}
[DEBUG] PlaintextKeys - session keys: {DEK=version=0 id=0 type=DES3 bytes=C89300
3C31DE189218C6FB138FB77B78 kcv=661A50, ENC=version=0 id=0 type=DES3 bytes=A0337C
32D4DEC016023AA576A157F4B1 kcv=6B8D49, MAC=version=0 id=0 type=DES3 bytes=23EB84
D3B9B9F9D1EAB3A8D6CD211B08 kcv=4608B7}
[DEBUG] GlobalPlatform - Verified card cryptogram: C5DFD309EDB24B73
[DEBUG] GlobalPlatform - Calculated host cryptogram: 9F499C19E050CDC5
A>> T=0 (4+0016) 84820100 10 9F499C19E050CDC5586977708B40EDCB
A<< (0000+2) (62ms) 9000
A>> T=0 (4+0008) 84CA00E0 08 E242BC68746C1C3C 00
A<< (0020+2) (62ms) E012C00401208010C00402208010C00403208010 9000
[DEBUG] GlobalPlatform - Replace: true
[DEBUG] GlobalPlatform - PUT KEY:version=1 id=1 type=DES3 bytes=6061626364656667
68696A6B6C6D6E6F kcv=9DCB14
[DEBUG] GlobalPlatform - PUT KEY:version=1 id=2 type=DES3 bytes=6061626364656667
68696A6B6C6D6E6F kcv=9DCB14
[DEBUG] GlobalPlatform - PUT KEY:version=1 id=3 type=DES3 bytes=6061626364656667
68696A6B6C6D6E6F kcv=9DCB14
A>> T=0 (4+0008) 84CA00E0 08 1E11C932000D57D5 00
A<< (0020+2) (62ms) E012C00401208010C00402208010C00403208010 9000
SCardEndTransaction()
SCardDisconnect("Excelsecu Reader 0", true)
Exception in thread "main" java.lang.IllegalArgumentException: Replacing keys an
d versions don't match existing?
        at pro.javacard.gp.GlobalPlatform.putKeys(GlobalPlatform.java:964)
        at pro.javacard.gp.GPTool.main(GPTool.java:793)
```

I listed the keys in the card and the key versions are all set to key version `32` which explains the problem with locking the card. How do I specify the key version when locking the card to clear the key version locking issue ?

```
>java -jar gp-official-v0_3_10_rc4.jar -info
GlobalPlatformPro v0.3.10rc4-0-gb81610e
Running on Windows 7 6.1 amd64, Java 1.8.0_151 by Oracle Corporation
Reader: XXXXXXXXXX Reader 0
ATR: 3B189657694C4C20181024
More information about your card:
    http://smartcard-atr.appspot.com/parse?ATR=3B189657694C4C20181024

Warning: no keys given, using default test key 404142434445464748494A4B4C4D4E4F
***** Card info:
[CPLC ICFabricator=008C, ICType=0089, OperatingSystemID=0000, OperatingSystemRel
easeDate=8297, OperatingSystemReleaseLevel=0100, ICFabricationDate=0000, ICSeria
lNumber=2B170AC0, ICBatchIdentifier=0000, ICModuleFabricator=0000, ICModulePacka
gingDate=0000, ICCManufacturer=0000, ICEmbeddingDate=0000, ICPrePersonalizer=000
0, ICPrePersonalizationEquipmentDate=0000, ICPrePersonalizationEquipmentID=00000
000, ICPersonalizer=0000, ICPersonalizationDate=0000, ICPersonalizationEquipment
ID=00000000]
VER:32 ID:1 TYPE:DES3 LEN:16
VER:32 ID:2 TYPE:DES3 LEN:16
VER:32 ID:3 TYPE:DES3 LEN:16
***** GET DATA:
IIN 420600005F49494E
CIN 450600005F43494E
SSC 03B3
*****
***** CARD DATA
Tag 6: 1.2.840.114283.1
-> Global Platform card
Tag 60: 1.2.840.114283.2.2.2
-> GP Version: 2.2
Tag 63: 1.2.840.114283.3
Tag 64: 1.2.840.114283.4.2.85
-> GP SCP02 i=55
Tag 65: 1.2.840.114283.2.1.1
-> GP Version: 1.1
Tag 66: 1.3.6.1.4.1.42.2.110.1.2
***** KEY INFO
VER:32 ID:1 TYPE:DES3 LEN:16
VER:32 ID:2 TYPE:DES3 LEN:16
VER:32 ID:3 TYPE:DES3 LEN:16
```

**Comment by martinpaljak** [comment]
That is some very-very old version. Please re-try with latest releas.e
