### ISSUE TITLE
problem when cap file too large

### ISSUE THREAD

**Issue by cocobear** [martinpaljak/GlobalPlatformPro#16]
I got  *" java.lang.ArrayIndexOutOfBoundsException"* when my cap file is *83KB*

It worked fine when I decrease cap file size to *73KB. *

Here it is trace log when I install my 83KB cap file.

```
gp -d -v  -install sjy71.cap
# Detected readers from SunPCSC
[*] OMNIKEY CardMan 1021 0
SCardConnect("OMNIKEY CardMan 1021 0", T=*) -> T=0, 3B9F95803FC7A08031E073FE2113
6701434F5357A101F2
SCardBeginTransaction("OMNIKEY CardMan 1021 0")
Reader: OMNIKEY CardMan 1021 0
ATR: 3B9F95803FC7A08031E073FE21136701434F5357A101F2
More information about your card:
    http://smartcard-atr.appspot.com/parse?ATR=3B9F95803FC7A08031E073FE211367014
34F5357A101F2

A>> T=0 (4+0000) 00A40400 00
A<< (0081+2) (31ms) 6F4F8410D1560001010001600000000100000000A53B7331732F06072A81
1C86FC6B01600C060A2A811C86FC6B02020101630906072A811C86FC6B03640B06092A811C86FC6B
0402159F6E010F9F6501FF 9000
Auto-detected ISD AID: D1560001010001600000000100000000
A>> T=0 (4+0008) 80500000 08 7946FBBBE2F9F3DF
A<< (0028+2) (18ms) 0182000000000000000020020236A74EFBEC430CC65C9DBE2055C8CB 900
0
Host challenge: 7946FBBBE2F9F3DF
Card challenge: 0236A74EFBEC430C
Card reports SCP02 with version 32 keys
Master keys:
Version 0
ENC: Ver:0 ID:0 Type:DES3 Len:16 Value:404142434445464748494A4B4C4D4E4F
MAC: Ver:0 ID:0 Type:DES3 Len:16 Value:404142434445464748494A4B4C4D4E4F
KEK: Ver:0 ID:0 Type:DES3 Len:16 Value:404142434445464748494A4B4C4D4E4F
Sequnce counter: 0236
Derived session keys:
Version 0
ENC: Ver:0 ID:0 Type:DES3 Len:16 Value:7CDFBDCFDEB3E13DDD26075E22CEE6FB
MAC: Ver:0 ID:0 Type:DES3 Len:16 Value:28AEB6F000838BB06BCFB1E3812A43F3
KEK: Ver:0 ID:0 Type:DES3 Len:16 Value:4367EBD1840B5353AB28F742EE0125FD
Verified card cryptogram: C65C9DBE2055C8CB
Calculated host cryptogram: 92F94A2E3ED1E091
A>> T=0 (4+0016) 84820100 10 92F94A2E3ED1E091CB6767E45D44E820
A<< (0000+2) (16ms) 9000
A>> T=0 (4+0010) 84F28000 0A 4F007919D70A56172156
A<< (0019+2) (10ms) 10D15600010100016000000001000000000F9A 9000
A>> T=0 (4+0010) 84F24000 0A 4F00AFDEFCEF9D98C98F
A<< (0061+2) (15ms) 09A0000001514352530007000CA000000063504B43532D313507000E3250
41592E5359532E444446303107000E315041592E5359532E44444630310700 9000
A>> T=0 (4+0010) 84F22000 0A 4F00C778C891C35B8907
A<< (0240+2) (33ms) 10D1560001010001610000000000000000010008A0000001514352530100
07A0000000620301010007A0000000620002010007A0000000620001010007A00000006200030100
07A0000000620101010008A000000062010101010007A0000000620102010007A000000062020101
0009A00000006202080101010007A000000062020301000FA0636F73770067707365727669636501
0006A00000015100010006A00000015102010010A0000000090003FFFFFFFF8910710001010010A0
000000090003FFFFFFFF891071000201000BA0636F7377000E00000E00010010A0000000090005FF
FFFFFF89110000000100 6310
A>> T=0 (4+0010) 84F22001 0A 4F00510F323D96C32586
A<< (0248+2) (35ms) 10A0000000090005FFFFFFFF8911010000010010A0000000090005FFFFFF
FF8913000000010010A0000000090005FFFFFFFF8912000000010010A0000000090005FFFFFFFF89
15000000010010A0000000871005FFFFFFFF8913100000010010A0000000871005FFFFFFFF891320
0000010008A0636F737700FE00010010A0000000090005FFFFFFFF8916010000010010A000000009
0005FFFFFFFF8916020100010010A0000000090005FFFFFFFF8916020200010010A0000000090005
FFFFFFFF89160203000100060A0300000002010010D15600010100016000FFFFFF02000000010010
D15600010100016000FFFFFF010000000100 6310
A>> T=0 (4+0010) 84F22001 0A 4F00C57E6F94BF22B001
A<< (0155+2) (25ms) 10A0636F7377696E7465726E616C41504901000BA0636F7377535A544150
4901000BA0636F7377535A5441504A01000BA0636F7377000C00000C00010009A000000062030101
0101000AD1560001010A030002080100060A03000000010100060A030000000301000A0A03000000
1CCE561F00010010D1560001018001600000050100000000010010D1560001018001600000050100
0000010100 9000
A>> T=0 (4+0010) 84F21000 0A 4F005C2D6BACA45EF706
A<< (0251+2) (35ms) 10D156000101000161000000000000000001000110D15600010100016110
0000000000000008A00000015143525301000109A0000001514352530007A0000000620301010000
07A000000062000201000007A000000062000101000007A000000062000301000007A00000006201
0101000008A00000006201010101000007A000000062010201000007A000000062020101000009A0
000000620208010101000007A00000006202030100000FA0636F7377006770736572766963650100
0006A0000001510001000006A0000001510201000010A0000000090003FFFFFFFF89107100010100
0010A0000000090003FFFFFFFF8910710002010000 6310
A>> T=0 (4+0010) 84F21001 0A 4F001BCB50BC1033E948
A<< (0247+2) (35ms) 0BA0636F7377000E00000E0001000010A0000000090005FFFFFFFF891100
000001000010A0000000090005FFFFFFFF891101000001000010A0000000090005FFFFFFFF891300
000001000010A0000000090005FFFFFFFF891200000001000010A0000000090005FFFFFFFF891500
000001000010A0000000871005FFFFFFFF891310000001000010A0000000871005FFFFFFFF891320
000001000008A0636F737700FE0001000010A0000000090005FFFFFFFF891601000001000010A000
0000090005FFFFFFFF891602010001000010A0000000090005FFFFFFFF891602020001000010A000
0000090005FFFFFFFF8916020300010000 6310
A>> T=0 (4+0010) 84F21001 0A 4F0034E84298047A9D58
A<< (0228+2) (33ms) 060A030000000201000010D15600010100016000FFFFFF02000000010000
10D15600010100016000FFFFFF0100000001000010A0636F7377696E7465726E616C415049010000
0BA0636F7377535A544150490100000BA0636F7377535A5441504A0100000BA0636F7377000C0000
0C0001000009A000000062030101010100000AD1560001010A030002080100010ED1560001015468
6DB50A03000208060A0300000001010000060A03000000030100000A0A030000001CCE561F000100
0010D156000101800160000005010000000001000110D1560001018001600000050200000000 631
0
A>> T=0 (4+0010) 84F21001 0A 4F003332EE6ACBAE52DB
A<< (0037+2) (12ms) 10D156000101800160000005010000000101000110D15600010180016000
00050200000001 9000
No manifest in CAP. Information from Header and Applet components:
Package: sjy71 v0.1 with AID D1560000403000635900505100000000
Applet: AID D1560000405000635900505100000000
Installing applet from package sjy71
A>> T=0 (4+0045) 84E60200 2D 10D156000040300063590050510000000010D15600010100016
00000000100000000000000D9D61F4C596EF23A
A<< (0001+2) (20ms) 9000
SCardEndTransaction()
SCardDisconnect("OMNIKEY CardMan 1021 0", false)
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException
        at java.lang.System.arraycopy(Native Method)
        at pro.javacard.gp.CapFile.getRawCode(CapFile.java:262)
        at pro.javacard.gp.CapFile.getLoadBlocks(CapFile.java:220)
        at pro.javacard.gp.GlobalPlatform.loadCapFile(GlobalPlatform.java:722)
        at pro.javacard.gp.GlobalPlatform.loadCapFile(GlobalPlatform.java:684)
        at pro.javacard.gp.GPTool.main(GPTool.java:448)

```

**Comment by cocobear** [comment]
This is  trace log useing -i -v -d
```
E:\sim-java\SRC\tools\JCTools\src>gp -d -v -i -install sjy71.cap
# Detected readers from SunPCSC
[*] OMNIKEY CardMan 1021 0
SCardConnect("OMNIKEY CardMan 1021 0", T=*) -> T=0, 3B9F95803FC7A08031E073FE2113
6701434F5357A101F2
SCardBeginTransaction("OMNIKEY CardMan 1021 0")
Reader: OMNIKEY CardMan 1021 0
ATR: 3B9F95803FC7A08031E073FE21136701434F5357A101F2
More information about your card:
    http://smartcard-atr.appspot.com/parse?ATR=3B9F95803FC7A08031E073FE211367014
34F5357A101F2

A>> T=0 (4+0000) 00A40400 00
A<< (0081+2) (31ms) 6F4F8410D1560001010001600000000100000000A53B7331732F06072A81
1C86FC6B01600C060A2A811C86FC6B02020101630906072A811C86FC6B03640B06092A811C86FC6B
0402159F6E010F9F6501FF 9000
Auto-detected ISD AID: D1560001010001600000000100000000
***** Card info:
A>> T=0 (4+0000) 80CA9F7F 00
A<< (0000+2) (5ms) 6A86
GET DATA(CPLC) returned SW: 6A86
NO CPLC
***** CARD DATA
A>> T=0 (4+0000) 80CA0066 00
A<< (0054+2) (12ms) 0066336631732F06072A811C86FC6B01600C060A2A811C86FC6B02020101
630906072A811C86FC6B03640B06092A811C86FC6B040215 9000
Unknown tag: 33
***** KEY INFO
A>> T=0 (4+0000) 80CA00E0 00
A<< (0053+2) (15ms) 00E032C00401208010C00402208010C00403208010C0060170A180A080C0
0401718010C00401018010C00402018010C00403018010 9000
SCardEndTransaction()
SCardDisconnect("OMNIKEY CardMan 1021 0", false)
Exception in thread "main" java.lang.RuntimeException: Expected tag ffffffe0 but
 had 0
        at pro.javacard.gp.TLVUtils.skip_tag_or_throw(TLVUtils.java:18)
        at pro.javacard.gp.GPData.get_key_template_list(GPData.java:122)
        at pro.javacard.gp.GlobalPlatform.getKeyInfoTemplate(GlobalPlatform.java
:268)
        at pro.javacard.gp.GPData.print_card_info(GPData.java:260)
        at pro.javacard.gp.GPTool.main(GPTool.java:341)

```

**Comment by martinpaljak** [comment]
For the loading error, please have a look at https://github.com/martinpaljak/GlobalPlatformPro/releases/tag/v0.3.3

For the other one, that code is just plainly bogus but the error looks weird. Will investigate.

**Comment by martinpaljak** [comment]
Also, what kind of card is it and does it qualify for the Buyer's Guide / TestedCards ?

https://github.com/martinpaljak/GlobalPlatformPro/blob/master/docs/JavaCardBuyersGuide/README.md#javacard-buyers-guide-of-2015

**Comment by cocobear** [comment]
It's CMCC(China Mobile)  USIM CARD  with NFC support .

**Comment by martinpaljak** [comment]
Did the change fix the loading problem ?

**Comment by martinpaljak** [comment]
For the unxpected tag issue, please give the output of `gp -version`

**Comment by cocobear** [comment]
yes, it is fixed. thank's for replying so fast.
I can't provide it this days, I away from work place , sorry.

**Comment by martinpaljak** [comment]
Okay. thanks for using.
