### ISSUE TITLE
New 19.05.16 version broke something

### ISSUE THREAD

**Issue by antonio-fr** [martinpaljak/GlobalPlatformPro#169]
We faced an issue with different cards, different readers, different machines, different OS. After investigation, it turns out the latest version broke things that worked before. Nothing fancy, low level communication is broken with our JCOP3 GP 2.1 cards. Maybe a new strict check, but I guess since there was a major refactoring of the app, there can be an issue that our config triggered.

Version n-1 we were used to run
```
$ java -jar gp190122.jar -l -dv

GlobalPlatformPro 19.01.22-0-gf94d7f5
Running on Linux 4.15.0-50-generic amd64, Java 11.0.3 by Oracle Corporation
# Detected readers from JNA2PCSC
[*] Alcor Micro AU9560 00 00
SCardConnect("Alcor Micro AU9560 00 00", T=*) -> T=1, 3BDC18FF8191FE1FC38073C821136605036351000250
SCardBeginTransaction("Alcor Micro AU9560 00 00")
Reader: Alcor Micro AU9560 00 00
ATR: 3BDC18FF8191FE1FC38073C821136605036351000250
More information about your card:
    http://smartcard-atr.appspot.com/parse?ATR=3BDC18FF8191FE1FC38073C821136605036351000250

A>> T=1 (4+0000) 00A40400 00 
A<< (0018+2) (26ms) 6F108408A000000151000000A5049F6501FF 9000
[TRACE] GlobalPlatform -  [6F]
[TRACE] GlobalPlatform -      [84] A000000151000000
[TRACE] GlobalPlatform -      [A5]
[TRACE] GlobalPlatform -          [9F65] FF
[DEBUG] GlobalPlatform - Auto-detected ISD: A000000151000000
Warning: no keys given, using default test key 404142434445464748494A4B4C4D4E4F
[TRACE] GlobalPlatform - Generated host challenge: EC255ADBCDB6C751
A>> T=1 (4+0008) 80500000 08 EC255ADBCDB6C751 00
A<< (0028+2) (61ms) 00007213002987072483FF02020613A5A6AADE027E59F3F8C98F0EE3 9000
[DEBUG] GlobalPlatform - Host challenge: EC255ADBCDB6C751
[DEBUG] GlobalPlatform - Card challenge: 020613A5A6AADE02
[DEBUG] GlobalPlatform - Card reports SCP02 with key version 255 (0xFF)
[DEBUG] GlobalPlatform - Will do SCP02 (8)
[DEBUG] PlaintextKeys - Card keys: {ENC=type=RAW bytes=404142434445464748494A4B4C4D4E4F, DEK=type=RAW bytes=404142434445464748494A4B4C4D4E4F, MAC=type=RAW bytes=404142434445464748494A4B4C4D4E4F}
[TRACE] PlaintextKeys - Session keys: {ENC=type=DES3 bytes=E1AE8F73B825C980A9C1DB9A51424B02 kcv=B4E7F3, DEK=type=DES3 bytes=504FC6CB6DD0D4AFB5F16CED604716E0 kcv=4696FF, MAC=type=DES3 bytes=2BF5C818AE462307CA24D77D5B58B799 kcv=684FB1}
[DEBUG] GlobalPlatform - Verified card cryptogram: 7E59F3F8C98F0EE3
[DEBUG] GlobalPlatform - Calculated host cryptogram: 7B627C131C9F2504
A>> T=1 (4+0016) 84820100 10 7B627C131C9F2504DB9EA975418032F3
A<< (0000+2) (39ms) 9000
A>> T=1 (4+0010) 84F28002 0A 4F006FF4D6FE7D569B9E 00
A<< (0044+2) (36ms) E32A4F08A0000001510000009F700101C5039EFE80C407A0000000620001CE020100CC08A000000151000000 9000
[TRACE] GPRegistry -  [E3]
[TRACE] GPRegistry -      [4F] A000000151000000
[TRACE] GPRegistry -      [9F70] 01
[TRACE] GPRegistry -      [C5] 9EFE80
[TRACE] GPRegistry -      [C4] A0000000620001
[TRACE] GPRegistry -      [CE] 0100
[TRACE] GPRegistry -      [CC] A000000151000000
A>> T=1 (4+0010) 84F24002 0A 4F0013954FDFA77C00B8 00
A<< (0042+2) (36ms) E3284F07A00000100001019F700107C503000000C406A00000100001CE020100CC08A000000151000000 9000
[TRACE] GPRegistry -  [E3]
[TRACE] GPRegistry -      [4F] A0000010000101
[TRACE] GPRegistry -      [9F70] 07
[TRACE] GPRegistry -      [C5] 000000
[TRACE] GPRegistry -      [C4] A00000100001
[TRACE] GPRegistry -      [CE] 0100
[TRACE] GPRegistry -      [CC] A000000151000000
A>> T=1 (4+0010) 84F22002 0A 4F00C253E172FF4CF769 00
A<< (0159+2) (52ms) E30D4F07A00000015153509F700101E3134F0DA00000016443686970446F63049F700101E3134F0DA00000016443686970446F63039F700101E3134F0DA00000016443686970446F63029F700101E3134F0DA00000016443686970446F63019F700101E3154F0FA000000396545300000001000405009F700101E3154F0FA000000396545300000001000607009F700101E30C4F06A000001000019F700101 9000
[TRACE] GPRegistry -  [E3]
[TRACE] GPRegistry -      [4F] A0000001515350
[TRACE] GPRegistry -      [9F70] 01
[TRACE] GPRegistry -  [E3]
[TRACE] GPRegistry -      [4F] A00000016443686970446F6304
[TRACE] GPRegistry -      [9F70] 01
[TRACE] GPRegistry -  [E3]
[TRACE] GPRegistry -      [4F] A00000016443686970446F6303
[TRACE] GPRegistry -      [9F70] 01
[TRACE] GPRegistry -  [E3]
[TRACE] GPRegistry -      [4F] A00000016443686970446F6302
[TRACE] GPRegistry -      [9F70] 01
[TRACE] GPRegistry -  [E3]
[TRACE] GPRegistry -      [4F] A00000016443686970446F6301
[TRACE] GPRegistry -      [9F70] 01
[TRACE] GPRegistry -  [E3]
[TRACE] GPRegistry -      [4F] A00000039654530000000100040500
[TRACE] GPRegistry -      [9F70] 01
[TRACE] GPRegistry -  [E3]
[TRACE] GPRegistry -      [4F] A00000039654530000000100060700
[TRACE] GPRegistry -      [9F70] 01
[TRACE] GPRegistry -  [E3]
[TRACE] GPRegistry -      [4F] A00000100001
[TRACE] GPRegistry -      [9F70] 01
A>> T=1 (4+0010) 84F21002 0A 4F00398785C288A5C8C0 00
A<< (0225+2) (67ms) E3174F07A00000015153509F7001018408A000000151535041E3134F0DA00000016443686970446F63049F700101E3134F0DA00000016443686970446F63039F700101E3134F0DA00000016443686970446F63029F700101E3234F0DA00000016443686970446F63019F700101840EA00000016443686970446F630101E3274F0FA000000396545300000001000405009F7001018410A0000003965453000000010004000000E3394F0FA000000396545300000001000607009F7001018410A00000039654530000000100060000008410A0000003965453000000010006000010 6310
A>> T=1 (4+0010) 84F21003 0A 4F005B3E24E3AF664BF8 00
A<< (0023+2) (32ms) E3154F06A000001000019F7001018407A0000010000101 9000
[TRACE] GPRegistry -  [E3]
[TRACE] GPRegistry -      [4F] A0000001515350
[TRACE] GPRegistry -      [9F70] 01
[TRACE] GPRegistry -      [84] A000000151535041
[TRACE] GPRegistry -  [E3]
[TRACE] GPRegistry -      [4F] A00000016443686970446F6304
[TRACE] GPRegistry -      [9F70] 01
[TRACE] GPRegistry -  [E3]
[TRACE] GPRegistry -      [4F] A00000016443686970446F6303
[TRACE] GPRegistry -      [9F70] 01
[TRACE] GPRegistry -  [E3]
[TRACE] GPRegistry -      [4F] A00000016443686970446F6302
[TRACE] GPRegistry -      [9F70] 01
[TRACE] GPRegistry -  [E3]
[TRACE] GPRegistry -      [4F] A00000016443686970446F6301
[TRACE] GPRegistry -      [9F70] 01
[TRACE] GPRegistry -      [84] A00000016443686970446F630101
[TRACE] GPRegistry -  [E3]
[TRACE] GPRegistry -      [4F] A00000039654530000000100040500
[TRACE] GPRegistry -      [9F70] 01
[TRACE] GPRegistry -      [84] A0000003965453000000010004000000
[TRACE] GPRegistry -  [E3]
[TRACE] GPRegistry -      [4F] A00000039654530000000100060700
[TRACE] GPRegistry -      [9F70] 01
[TRACE] GPRegistry -      [84] A0000003965453000000010006000000
[TRACE] GPRegistry -      [84] A0000003965453000000010006000010
[TRACE] GPRegistry -  [E3]
[TRACE] GPRegistry -      [4F] A00000100001
[TRACE] GPRegistry -      [9F70] 01
[TRACE] GPRegistry -      [84] A0000010000101
ISD: A000000151000000 (OP_READY)
     Parent:  A000000151000000
     From:    A0000000620001
     Privs:   SecurityDomain, CardLock, CardTerminate, CardReset, CVMManagement, TrustedPath, AuthorizedManagement, TokenVerification, GlobalDelete, GlobalLock, GlobalRegistry, FinalApplication, ReceiptGeneration

APP: A0000010000101 (SELECTABLE) (|.......|)
     Parent:  A000000151000000
     From:    A00000100001
     Privs:   

PKG: A0000001515350 (LOADED) (|....QSP|)
     Applet:  A000000151535041 (|....QSPA|)

PKG: A00000016443686970446F6304 (LOADED) (|....dChipDoc.|)

PKG: A00000016443686970446F6303 (LOADED) (|....dChipDoc.|)

PKG: A00000016443686970446F6302 (LOADED) (|....dChipDoc.|)

PKG: A00000016443686970446F6301 (LOADED) (|....dChipDoc.|)
     Applet:  A00000016443686970446F630101 (|....dChipDoc..|)

PKG: A00000039654530000000100040500 (LOADED) (|.....TS........|)
     Applet:  A0000003965453000000010004000000 (|.....TS.........|)

PKG: A00000039654530000000100060700 (LOADED) (|.....TS........|)
     Applet:  A0000003965453000000010006000000 (|.....TS.........|)
     Applet:  A0000003965453000000010006000010 (|.....TS.........|)

PKG: A00000100001 (LOADED) (|......|)
     Applet:  A0000010000101 (|.......|)

SCardEndTransaction(Alcor Micro AU9560 00 00)
SCardDisconnect("Alcor Micro AU9560 00 00", true)

```

With the new version 
```
$ java -jar gp190516.jar -l -dv

GlobalPlatformPro 19.05.16-0-g0014bda
Running on Linux 4.15.0-50-generic amd64, Java 11.0.3 by Oracle Corporation
# Detected readers from JNA2PCSC
[*] Alcor Micro AU9560 00 00
SCardConnect("Alcor Micro AU9560 00 00", T=*) -> T=1, 3BDC18FF8191FE1FC38073C821136605036351000250
SCardBeginTransaction("Alcor Micro AU9560 00 00")
Reader: Alcor Micro AU9560 00 00
ATR: 3BDC18FF8191FE1FC38073C821136605036351000250
More information about your card:
    http://smartcard-atr.appspot.com/parse?ATR=3BDC18FF8191FE1FC38073C821136605036351000250

A>> T=1 (4+0000) 00A40400 00 
A<< (0018+2) (28ms) 6F108408A000000151000000A5049F6501FF 9000
[TRACE] GPSession -  [6F]
[TRACE] GPSession -      [84] A000000151000000
[TRACE] GPSession -      [A5]
[TRACE] GPSession -          [9F65] FF
[DEBUG] GPSession - Auto-detected ISD: A000000151000000
Warning: no keys given, using default test key 404142434445464748494A4B4C4D4E4F
[WARN] PlaintextKeys - Don't know how to calculate KCV, defaulting to SCP02
[WARN] PlaintextKeys - Don't know how to calculate KCV, defaulting to SCP02
[WARN] PlaintextKeys - Don't know how to calculate KCV, defaulting to SCP02
[INFO] GPSession - Using card master keys: ENC=404142434445464748494A4B4C4D4E4F (KCV: 8BAF47) MAC=404142434445464748494A4B4C4D4E4F (KCV: 8BAF47) DEK=404142434445464748494A4B4C4D4E4F (KCV: 8BAF47) for null
[TRACE] GPSession - Generated host challenge: FF601EEC6CDB4845
A>> T=1 (4+0008) 80500000 08 FF601EEC6CDB4845 00
A<< (0028+2) (62ms) 00007213002987072483FF0202073B68941FA7CBFC04082C4F6F1042 9000
[DEBUG] GPSession - Host challenge: FF601EEC6CDB4845
[DEBUG] GPSession - Card challenge: 02073B68941FA7CB
[DEBUG] GPSession - Card reports SCP02 with key version 255 (0xFF)
[DEBUG] GPSession - Will do SCP0SCP02
[INFO] GPSession - Diversified card keys: ENC=404142434445464748494A4B4C4D4E4F (KCV: 8BAF47) MAC=404142434445464748494A4B4C4D4E4F (KCV: 8BAF47) DEK=404142434445464748494A4B4C4D4E4F (KCV: 8BAF47) for SCP02
[INFO] GPSession - Session keys: ENC=5F53DDF93EA7770E6DAD5BDBC01D3AF7 MAC=02C8F709003489C506901CB9A5B7E1EB RMAC=51DAE3F22145A17C937409C78A676B64, card keys=ENC=404142434445464748494A4B4C4D4E4F (KCV: 8BAF47) MAC=404142434445464748494A4B4C4D4E4F (KCV: 8BAF47) DEK=404142434445464748494A4B4C4D4E4F (KCV: 8BAF47) for SCP02
[DEBUG] GPSession - Verified card cryptogram: FC04082C4F6F1042
[DEBUG] GPSession - Calculated host cryptogram: E9A2075AC8AF72B9
SCardEndTransaction("Alcor Micro AU9560 00 00")
SCardDisconnect("Alcor Micro AU9560 00 00", true) tx:19/rx:50
Exception in thread "main" java.lang.IllegalArgumentException: Invalid APDU: length=21, b1=8
	at apdu4j.CommandAPDU.<init>(CommandAPDU.java:1295)
	at pro.javacard.gp.SCP0102Wrapper.wrap(SCP0102Wrapper.java:214)
	at pro.javacard.gp.GPSession.transmit(GPSession.java:524)
	at pro.javacard.gp.GPSession.openSecureChannel(GPSession.java:505)
	at pro.javacard.gp.GPTool.main(GPTool.java:337)

```

We got `java.lang.IllegalArgumentException: Invalid APDU: length=21, b1=8` with any commands such as delete, install,... on any OS, with 2 different readers models.

Here's a card capabilities :
```
[WARN] GPData - Invalid CPLC date: 011B
CPLC: ICFabricator=4790
      ICType=0503
      OperatingSystemID=8211
      OperatingSystemReleaseDate=6351 (2016-12-16)
      OperatingSystemReleaseLevel=0302
      ICFabricationDate=7213 (2017-08-01)
      ICSerialNumber=00298707
      ICBatchIdentifier=2483
      ICModuleFabricator=4E30
      ICModulePackagingDate=5037 (2015-02-06)
      ICCManufacturer=3331
      ICEmbeddingDate=4253 (2014-09-10)
      ICPrePersonalizer=5131
      ICPrePersonalizationEquipmentDate=3030 (2013-01-30)
      ICPrePersonalizationEquipmentID=32393837
      ICPersonalizer=1300
      ICPersonalizationDate=011B (invalid date format)
      ICPersonalizationEquipmentID=23893ED1

IIN: 420100
CIN: 45080000000000000000
Card Data: 
Tag 6: 1.2.840.114283.1
-> Global Platform card
Tag 60: 1.2.840.114283.2.2.1.1
-> GP Version: 2.1.1
Tag 63: 1.2.840.114283.3
Tag 64: 1.2.840.114283.4.2.85
-> GP SCP02 i=55
Tag 66: 1.3.6.1.4.1.42.2.110.1.2
-> JavaCard v2
Card Capabilities: 
[WARN] GPData - Bogus data detected, fixing double tag
Supports: SCP02 i=55
Supports: SCP03 i=00 i=10 with AES-128 AES-196 AES-256
Supported DOM privileges: SecurityDomain, CardLock, CardTerminate, CardReset, CVMManagement, TrustedPath, AuthorizedManagement, TokenVerification, GlobalDelete, GlobalLock, GlobalRegistry, FinalApplication, ReceiptGeneration
Supported APP privileges: CardLock, CardTerminate, CardReset, CVMManagement, FinalApplication, GlobalService
Supported LFDB hash: 02
Supported Token Verification ciphers: 01020840
Supported Receipt Generation ciphers: 0408
Supported DAP Verification ciphers: 01020840
Supported ECC Key Parameters: 0102030405
Version: 255 (0xFF) ID:   1 (0x01) type: DES3 length:  16 
Version: 255 (0xFF) ID:   2 (0x02) type: DES3 length:  16 
Version: 255 (0xFF) ID:   3 (0x03) type: DES3 length:  16 
```

**Comment by cheburashka** [comment]
Hi Antonio, I noticed your cards are configured for SCP02 option 02 (one secure channel base key instead of three). I think that's an invalid option. The default in JCOP is 15 and GP states that the ISD shall support at least one of '15', '1A' or '55'. The trace changed from: `Will do SCP02 (8)` to `Will do SCP0SCP02`. It's probably chocking with that option, I suggest you try changing back to 15.

**Comment by martinpaljak** [comment]
Please do try the "next" branch which should have this issue fixed. There's some maintenance work going on with switching from Travis to Github Actions but this requires some currently non-existing time.

**Comment by martinpaljak** [comment]
This should be fixed in the latest pre-release 19.06.16. Please re-try and report back.

**Comment by cheburashka** [comment]
Just to let you know that version 19.06.16 works for me, both with SCP02 i=15 and SCP03 i=60

**Comment by antonio-fr** [comment]
I can confirm this new version fixes this issue. Thanks.
