### ISSUE TITLE
Error: INSTALL [for install and make selectable] failed: 0x6A80 on sysmoUSIM-sjs1

### ISSUE THREAD

**Issue by Bartolosh** [martinpaljak/GlobalPlatformPro#293]
Hi, I was trying to load and install a Javacard applet that I developed on a sysmoUSIM-SJS1 using a PCSC-reader and GlobalPlatform Pro.
Trying to install applets that import only javacard libs, it works, but if they use sim.toolkit or sim.access libs, it gives me the 0x6A80 error and I think that is something linked to the import of the libs (I am using the ones suggested from sysmocom, ETSI TS 101 476 V7.0.0. In addiction to this if I use this version, ant-javacard says that the exp file is ill-formed, but if I use the 7.4.0 version, the build phase goes fine but then GlobalPlatform gives me the same error of before).

Here it is the output of ```gp -dvi -install applet.cap```:

```
# 
# gp -dvi -install bin/EmptyApplet.cap
SCardConnect("HID Global OMNIKEY 6121 Smart Card Reader [OMNIKEY 6121 Smart Card Reader] 00 00", T=*) -> T=0, 3B9F96801FC78031A073BE21136743200718000001A5
# GlobalPlatformPro 325fe84
# Running on Linux 5.15.41-1-lts amd64, Java 1.8.0_332 by Oracle Corporation
A>> T=0 (4+0000) 00A40400 00 
A<< (0071+2) (174ms) 6F458408A000000003000000A539732F06072A864886FC6B01600C060A2A864886FC6B02020101630906072A864886FC6B03640B06092A864886FC6B0402159F6E01079F6501FE 9000
[DEBUG] GPSession - Auto-detected ISD: A000000003000000
A>> T=0 (4+0000) 80CA9F7F 00 
A<< (0045+2) (10ms) 9F7F2AFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 9000
[WARN] GPData - Invalid CPLC date: FFFF
[WARN] GPData - Invalid CPLC date: FFFF
[WARN] GPData - Invalid CPLC date: FFFF
[WARN] GPData - Invalid CPLC date: FFFF
[WARN] GPData - Invalid CPLC date: FFFF
[WARN] GPData - Invalid CPLC date: FFFF
CPLC: ICFabricator=FFFF
      ICType=FFFF
      OperatingSystemID=FFFF
      OperatingSystemReleaseDate=FFFF (invalid date format)
      OperatingSystemReleaseLevel=FFFF
      ICFabricationDate=FFFF (invalid date format)
      ICSerialNumber=FFFFFFFF
      ICBatchIdentifier=FFFF
      ICModuleFabricator=FFFF
      ICModulePackagingDate=FFFF (invalid date format)
      ICCManufacturer=FFFF
      ICEmbeddingDate=FFFF (invalid date format)
      ICPrePersonalizer=FFFF
      ICPrePersonalizationEquipmentDate=FFFF (invalid date format)
      ICPrePersonalizationEquipmentID=FFFFFFFF
      ICPersonalizer=FFFF
      ICPersonalizationDate=FFFF (invalid date format)
      ICPersonalizationEquipmentID=FFFFFFFF

A>> T=0 (4+0000) 80CA0042 00 
A<< (0004+2) (10ms) 42020102 9000
IIN: 42020102
A>> T=0 (4+0000) 80CA0045 00 
A<< (0004+2) (9ms) 45020506 9000
CIN: 45020506
Card Data: 
A>> T=0 (4+0000) 80CA0066 00 
A<< (0051+2) (13ms) 6631732F06072A864886FC6B01600C060A2A864886FC6B02020101630906072A864886FC6B03640B06092A864886FC6B040215 9000
Tag 6: 1.2.840.114283.1
-> Global Platform card
Tag 60: 1.2.840.114283.2.2.1.1
-> GP Version: 2.1.1
Tag 63: 1.2.840.114283.3
Tag 64: 1.2.840.114283.4.2.21
-> GP SCP02 i=15
Card Capabilities: 
A>> T=0 (4+0000) 80CA0067 00 
A<< (0000+2) (8ms) 6A88
[DEBUG] GPData - GET DATA(Card Capabilities): N/A
A>> T=0 (4+0000) 80CA00E0 00 
A<< (0056+2) (16ms) E036C00401018010C00402018010C00403018010C00401028010C00402028010C00403028010C00401038010C00402038010C00403038010 9000
Version:   1 (0x01) ID:   1 (0x01) type: DES3         length:  16
Version:   1 (0x01) ID:   2 (0x02) type: DES3         length:  16
Version:   1 (0x01) ID:   3 (0x03) type: DES3         length:  16
Version:   2 (0x02) ID:   1 (0x01) type: DES3         length:  16
Version:   2 (0x02) ID:   2 (0x02) type: DES3         length:  16
Version:   2 (0x02) ID:   3 (0x03) type: DES3         length:  16
Version:   3 (0x03) ID:   1 (0x01) type: DES3         length:  16
Version:   3 (0x03) ID:   2 (0x02) type: DES3         length:  16
Version:   3 (0x03) ID:   3 (0x03) type: DES3         length:  16

Warning: no keys given, defaulting to 404142434445464748494A4B4C4D4E4F
[INFO] GPSession - Using card master keys with version 0 for setting up session [MAC] 
A>> T=0 (4+0008) 80500000 08 C6801BA536ADA0EE 00
A<< (0028+2) (13ms) 0A0AF0F1F0F2F0F0FFFF010200BA49B1C3C74527943AC97F115893AC 9000
[DEBUG] GPSession - SSC: 00BA
[DEBUG] GPSession - Host challenge: C6801BA536ADA0EE
[DEBUG] GPSession - Card challenge: 00BA49B1C3C74527
[DEBUG] GPSession - Card reports SCP02 with key version 1 (0x01)
[INFO] GPSession - Diversified card keys: ENC=404142434445464748494A4B4C4D4E4F (KCV: 8BAF47) MAC=404142434445464748494A4B4C4D4E4F (KCV: 8BAF47) DEK=404142434445464748494A4B4C4D4E4F (KCV: 8BAF47) for SCP02
[INFO] GPSession - Session keys: ENC=34EA43C9F49F940A7ADB770F3B6212AC MAC=CECC377C900FC6369D42842C6250F3C6 RMAC=72BCD16AE4574BF523D392BE998D35F3
[DEBUG] GPSession - Verified card cryptogram: 943AC97F115893AC
[DEBUG] GPSession - Calculated host cryptogram: F6E56FC0A5B3A9C9
A>> T=0 (4+0016) 84820100 10 F6E56FC0A5B3A9C9A511AD93A4AD4261
A<< (0000+2) (23ms) 9000
CAP file (v2.1), contains: applets for JavaCard 2.2.1
Package: emptyapplet D07002CA44 v1.0
Applet:  emptyapplet.EmptyApplet D07002CA44900101
Import:  A0000000620101                   v1.2 javacard.framework
Import:  A0000000090003FFFFFFFF8910710002 v2.1 sim.toolkit
Import:  A0000000620001                   v1.0 java.lang
Generated by Oracle Corporation converter  [v3.0.5]
On Tue May 31 11:29:57 CEST 2022 with JDK 1.8.0_332 (Oracle Corporation)
Code size 308 bytes (457 with debug)
SHA-256 f984a36aa93f81de0114964128f551947442265037833d6e23b18834daba3d50
SHA-1   be4c425fc7dcdf01a830429169dc87b0308cceef
A>> T=0 (4+0010) 84F28002 0A 4F00D0B272B110454D17 00
A<< (0019+2) (11ms) E3114F08A0000000030000009F700107C5019A 9000
A>> T=0 (4+0010) 84F24002 0A 4F007DEF783DACA09711 00
A<< (0145+2) (17ms) E3818E4F10A0000000090001FFFFFFFF89000000009F700107C501044F10A0000000090001FFFFFFFF89000000019F700107C501004F10A0000000090001FFFFFFFF89B00010019F700107C501004F10FF434E525810400402030000B00011009F700107C501004F10A0000000871002FFFFFFFF89070900009F700107C501004F0801020304050607089F700107C50100 9000
A>> T=0 (4+0010) 84F21002 0A 4F002557811474F4953C 00
A<< (0149+2) (18ms) E381924F0DA0000000090001FFFFFFFF89009F7001018410A0000000090001FFFFFFFF8900000000840FA0000000090001FFFFFFFF89B000104F0DA0000000871002FF49FFFF89009F7001018410A0000000871002FF49FFFF89040B00004F0AFF434E525810400402039F7001018410FF434E525810400402030000000000004F0501020304059F70010184080102030405060708 9000
A>> T=0 (4+0010) 84F22002 0A 4F00DAC51DBCF9AF7D92 00
A<< (0067+2) (14ms) E3414F0DA0000000090001FFFFFFFF89009F7001014F0DA0000000871002FF49FFFF89009F7001014F0AFF434E525810400402039F7001014F0501020304059F700101 9000
A>> T=0 (4+0026) 84E60200 1A 05D07002CA4408A00000000300000000000076A67800D89023BD
A<< (0001+2) (11ms) 00 9000
A>> T=0 (4+0255) 84E80000 FF C482013401000FDECAFFED010204000105D07002CA4402001F000F001F000C0028001A0022004B0026000A0000009200040002001603010004002803020107A0000000620101010210A0000000090003FFFFFFFF8910710002000107A000000062000103000C0108D07002CA44900101000106002243800302000107020000003700418002008101010881000000820000FF000100000007004B0005308F00013D181D1E8C00003B7A0243188C0002191E2529041E160441044131191E2529051E160541044131191E252906188B00037A0120188B000460037A7A00207A0110188C00057A08002600040002000203000B656D70747961AA218265621A86CF
A<< (0001+2) (125ms) 00 9000
A>> T=0 (4+0073) 84E88001 49 70706C657403000B456D7074794170706C65740000000005001A00060600000F010000000680030003800301038003030682000009000A0000000604070821070D5970C9CBE9ED51FE
A<< (0001+2) (623ms) 00 9000
CAP loaded
A>> T=0 (4+0010) 84F28002 0A 4F0075CC442E869B3A36 00
A<< (0019+2) (12ms) E3114F08A0000000030000009F700107C5019A 9000
A>> T=0 (4+0010) 84F24002 0A 4F00A85E90DCCE660009 00
A<< (0145+2) (16ms) E3818E4F10A0000000090001FFFFFFFF89000000009F700107C501044F10A0000000090001FFFFFFFF89000000019F700107C501004F10A0000000090001FFFFFFFF89B00010019F700107C501004F10FF434E525810400402030000B00011009F700107C501004F10A0000000871002FFFFFFFF89070900009F700107C501004F0801020304050607089F700107C50100 9000
A>> T=0 (4+0010) 84F21002 0A 4F008DD2185CD67ECA57 00
A<< (0170+2) (18ms) E381A74F0DA0000000090001FFFFFFFF89009F7001018410A0000000090001FFFFFFFF8900000000840FA0000000090001FFFFFFFF89B000104F0DA0000000871002FF49FFFF89009F7001018410A0000000871002FF49FFFF89040B00004F0AFF434E525810400402039F7001018410FF434E525810400402030000000000004F0501020304059F700101840801020304050607084F05D07002CA449F7001018408D07002CA44900101 9000
A>> T=0 (4+0010) 84F22002 0A 4F00DDFE75FE5BC468EF 00
A<< (0078+2) (14ms) E34C4F0DA0000000090001FFFFFFFF89009F7001014F0DA0000000871002FF49FFFF89009F7001014F0AFF434E525810400402039F7001014F0501020304059F7001014F05D07002CA449F700101 9000
A>> T=0 (4+0038) 84E60C00 26 05D07002CA4408D07002CA4490010108D07002CA44900101010002C900007F79A7EBEF99850E
A<< (0000+2) (5s487ms) 6A80
Error: INSTALL [for install and make selectable] failed: 0x6A80 (Wrong data/incorrect values in data)
pro.javacard.gp.GPException: INSTALL [for install and make selectable] failed: 0x6A80 (Wrong data/incorrect values in data)
	at pro.javacard.gp.GPException.check(GPException.java:64)
	at pro.javacard.gp.GPSession.installAndMakeSelectable(GPSession.java:624)
	at pro.javacard.gp.GPTool.run(GPTool.java:473)
	at pro.javacard.gp.GPTool.main(GPTool.java:107)
SCardDisconnect("HID Global OMNIKEY 6121 Smart Card Reader [OMNIKEY 6121 Smart Card Reader] 00 00", true) tx:610/rx:1096
```

Can someone help me? Thanks

**Comment by sulqadari** [comment]
According to ETSI TS 102 226, clause 8.2.1.3.2, depending on framefork to be used, command data field of the INSTALL [for install] command shall contain CA tag (Tag of SIM file access and toolkit application specific parameters field (resides under EF tag)) or EA tag (Tag of UICC System Specific Parameters constructed field)

**Comment by martinpaljak** [comment]
Probable cause: you need to set the right installation parameters required by SIM cards.

**Comment by martinpaljak** [comment]
If you take the time to figure out the minimum set of installation parameters that are needed for SIM, do let me know and I can add it to documentation or maybe add a command line option for simple adjustments.

**Comment by sulqadari** [comment]
Also the problem that I encountered with was that the version of my JCVM was 2.2.2, while I tried to install applet versioned 3.0.4 onto it. When I compiled the .CAP file with appropriate JCDK the issui was solved.

**Comment by martinpaljak** [comment]
In that case you should not be able to load it either? Anyway, what kind of installation parameters, if any, are needed for installation?

**Comment by sulqadari** [comment]
My bad. You're right: wrong JCDK version wouldn't allow to install an applet at all. 
As I mentioned in first comment, the problem was in misunderstanding of what kind of parameters would I provide with INSTALL for install. In my case the CA tag was right one

**Comment by martinpaljak** [comment]
Care to give exact parameters?

**Comment by sulqadari** [comment]
Yes, ofcourse, tomorrow I'll post here the params I use in my project

**Comment by sulqadari** [comment]
Here is the params I actually use in the project:

```
80 E6 0C 00 69
    10 A0 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F    //pack AID
    10 A0 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E FF    //exec module AID
    10 A0 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E FF    //app AID
    01 00     //privileges
    32        // Length of Install Parameters field
        C9 1B        // Application Specific Parameters
            03        // max attempts
            04 04 81 00 00        // imei address
            04 04 81 01 01        // mca address
            FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF// default key
        EF 13        // System Specific TLV
            CA 0E        // SIM File Access and Toolkit Application Specific Parameters Tag
            01 00        // Access Domain LV
            FF        // Priority level of the Toolkit application instance
            00        // Maximum number of timers allowed for this application instance
            00        // Maximum text length for a menu entry
            00        // Maximum number of menu entries allowed for this application instance
            00        // Maximum number of channels for this application instance
            02 01 16        // MSL LV
            03 42 42 42        // TAR LV
            CF 01 00        // Implicit selection parameter (present in combined [for install and make selectable])
    00        // Length of Install Token
```
I hope this specimen pasted as is (with little substitutions) will be helpful.
Please note that I use my proprietary script written in Java thus one's have to fit these params into appropriate places in gp.

**Comment by sulqadari** [comment]
@goo99x you are welcome.
In my example I messed up with indentations, and have just corrected that, check it out.

Look, according to Global Platform, clause 11.5.2.3.2, table 11-43, the outer structure of params is as follows:
right after privileges tag-length struct (0x01 0x00), the length value of install params shall follow (in my example the values right after 0x32).
Both tag 0xCA and 0xCF resides under tag 0xEF, and the latter is at the same level with 0xC9 tag (app specific params).

the last 0x00 byte is at the same level as the 0x32.

The details of install params filed you can find in table 11-49 in Global Platform spec.

**Comment by martinpaljak** [comment]
GPPro tries to be helpful for "simple" use cases where the only installation parameters are application parameters (C9) and automatically wraps things with 0xC9 and with right length, _unless_ the parameters start with 0xC9 and thus are expected to be properly formatted parameters blob and include other values (like here, system parameters under 0xEF).

This has seemed like a usable approach this far. Any other suggestions? The principle here should be "make common and simple things simple, but complex things possible". Maybe "--sys-params" ?

On equal note, load parameters are currently not exposed via CLI either.

**Comment by sulqadari** [comment]
> Maybe "--sys-params"

Sounds good. Also it would be nice to add support for 0xEA tag, which is indended to be used when we dealing with UICC applet.

**Comment by sulqadari** [comment]
It really sounds like a good idea: let it be some simple tools for common and simple projects. But for advanced projects a kind of universal builder of constructed TLVs.
