### ISSUE TITLE
External authenticate failed

### ISSUE THREAD

**Issue by aanno** [martinpaljak/GlobalPlatformPro#39]
I'm trying to list my fidesmo card with GlobalPlatformPro v0.3.4, however:

```
$ java -jar ~/Downloads/gp.jar --relax -v -list 
Reader: SCL011 Contactless Reader [SCL01x Contactless Reader] (21161045208718) 00 00
ATR: 3B8980014A434F5032343252324A
More information about your card:
    http://smartcard-atr.appspot.com/parse?ATR=3B8980014A434F5032343252324A

Auto-detected ISD AID: A000000151000000
Host challenge: 4849A29D9FCFC9E3
Card challenge: 001D47D2B3096958
Card reports SCP02 with version 1 keys
Master keys: 
Version 0
ENC: Ver:0 ID:0 Type:DES3 Len:16 Value:404142434445464748494A4B4C4D4E4F
MAC: Ver:0 ID:0 Type:DES3 Len:16 Value:404142434445464748494A4B4C4D4E4F
KEK: Ver:0 ID:0 Type:DES3 Len:16 Value:404142434445464748494A4B4C4D4E4F
Sequnce counter: 001D
Derived session keys: 
Version 0
ENC: Ver:0 ID:0 Type:DES3 Len:16 Value:1526478F541984920D6C39016463B195
MAC: Ver:0 ID:0 Type:DES3 Len:16 Value:B3DC47CE007033D288B4EA273EE5C0F5
KEK: Ver:0 ID:0 Type:DES3 Len:16 Value:262AC040EA69227BD7FD5CDE2353454A
STRICT WARNING: Card cryptogram invalid!
Card: 2E4165CBA9B207F6
Host: 573B9A89EBF78EA3
!!! DO NOT RE-TRY THE SAME COMMAND/KEYS OR YOU MAY BRICK YOUR CARD !!!
Calculated host cryptogram: 8234791221A1FEBE
pro.javacard.gp.GPException: External authenticate failed SW: 6982
        at pro.javacard.gp.GlobalPlatform.check(GlobalPlatform.java:1092)
        at pro.javacard.gp.GlobalPlatform.openSecureChannel(GlobalPlatform.java:534)
        at pro.javacard.gp.GPTool.main(GPTool.java:371)
```
Am I doing something silly? Is it because I don't give the User PIN?

Kind regards,

aanno

**Comment by martinpaljak** [comment]
Yes. Fidesmo is a closed platform (they have the GP keys, not you) so this tool is useless with your card. As the README tells: you need to know (and specify, with `-key`) the card keys

**Comment by aanno** [comment]
Thank you very much, I was not aware of this, but I guess it is in their blog at http://about.fidesmo.com/why-doesnt-fidesmo-use-default-isd-keys/ .

I've got a idea what is a similar card and where could I buy it (_incl_ the ISD key)?

**Comment by martinpaljak** [comment]
https://github.com/martinpaljak/GlobalPlatformPro/tree/master/docs/JavaCardBuyersGuide has linx. Fidesmo is a NXP, so motechno.com maybe.
