### ISSUE TITLE
DESFire EV1 lead to java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by 0xbaadf00d** [martinpaljak/GlobalPlatformPro#40]
Hi,

I'm trying to use your tool with a `Mifare DESFire EV1` and `Prox'n'Roll PC/SC Reader from SpringCard` but I get exceptions on all cases.
#### Version

```
P:\Users\zero\Downloads>java -jar gp.jar -V
GlobalPlatformPro v0.3.7
Running on Windows 10 10.0 amd64, Java 1.8.0_74 by Oracle Corporation
```
#### Try 1 (Without specified ISD)

```
P:\Users\zero\Downloads>java -jar gp.jar -lvdi
[DEBUG] PlaintextKeys - static keys:
ENC: Ver:0 ID:0 Type:DES3 Len:16 Value:404142434445464748494A4B4C4D4E4F
MAC: Ver:0 ID:0 Type:DES3 Len:16 Value:404142434445464748494A4B4C4D4E4F
KEK: Ver:0 ID:0 Type:DES3 Len:16 Value:404142434445464748494A4B4C4D4E4F
# Detected readers from JNA2PCSC
[*] SpringCard Prox'N'Roll 0
SCardConnect("SpringCard Prox'N'Roll 0", T=*) -> T=1, 3B8180018080
SCardBeginTransaction("SpringCard Prox'N'Roll 0")
Reader: SpringCard Prox'N'Roll 0
ATR: 3B8180018080
More information about your card:
    http://smartcard-atr.appspot.com/parse?ATR=3B8180018080

A>> T=1 (4+0000) 00A40400 00
A<< (0000+2) (3ms) 6A87
***** Card info:
A>> T=1 (4+0000) 80CA9F7F 00
A<< (0000+2) (2ms) 6E00
A>> T=1 (4+0000) 00CA9F7F 00
A<< (0000+2) (2ms) 6D00
[DEBUG] GlobalPlatform - GET DATA(CPLC) returned SW: 6D00
NO CPLC
***** CARD DATA
A>> T=1 (4+0000) 80CA0066 00
A<< (0000+2) (2ms) 6E00
NO CARD DATA
***** KEY INFO
A>> T=1 (4+0000) 80CA00E0 00
A<< (0000+2) (1ms) 6E00
A>> T=1 (4+0000) 00CA00E0 00
A<< (0000+2) (2ms) 6D00
[DEBUG] GlobalPlatform - GET DATA(Key Information Template) not supported
SCardEndTransaction()
SCardDisconnect("SpringCard Prox'N'Roll 0", true)
Exception in thread "main" java.lang.IllegalStateException: No selected ISD!
        at pro.javacard.gp.GlobalPlatform.openSecureChannel(GlobalPlatform.java:365)
        at pro.javacard.gp.GPTool.main(GPTool.java:410)
```
#### Try 2 (with ISD)

```
P:\Users\zero\Downloads>java -jar gp.jar --sdaid D2760000850100 -lvdi
[DEBUG] PlaintextKeys - static keys:
ENC: Ver:0 ID:0 Type:DES3 Len:16 Value:404142434445464748494A4B4C4D4E4F
MAC: Ver:0 ID:0 Type:DES3 Len:16 Value:404142434445464748494A4B4C4D4E4F
KEK: Ver:0 ID:0 Type:DES3 Len:16 Value:404142434445464748494A4B4C4D4E4F
# Detected readers from JNA2PCSC
[*] SpringCard Prox'N'Roll 0
SCardConnect("SpringCard Prox'N'Roll 0", T=*) -> T=1, 3B8180018080
SCardBeginTransaction("SpringCard Prox'N'Roll 0")
Reader: SpringCard Prox'N'Roll 0
ATR: 3B8180018080
More information about your card:
    http://smartcard-atr.appspot.com/parse?ATR=3B8180018080

A>> T=1 (4+0007) 00A40400 07 D2760000850100 00
A<< (0000+2) (4ms) 9000
SCardEndTransaction()
SCardDisconnect("SpringCard Prox'N'Roll 0", true)
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 0
        at pro.javacard.gp.TLVUtils.expectTag(TLVUtils.java:35)
        at pro.javacard.gp.TLVUtils.skipTagAndLength(TLVUtils.java:41)
        at pro.javacard.gp.GlobalPlatform.select(GlobalPlatform.java:225)
        at pro.javacard.gp.GPTool.main(GPTool.java:385)
```

**Comment by SuperVirus** [comment]
The GlobalPlatform tool is for managing javacards.
Your DESFire EV1 is only a secured memory card, but no javacard.

**Comment by martinpaljak** [comment]
Thanks @SuperVirus. Yes, GPPro is for JavaCard-s and having a more strict check (and a helpful message in the command line tool) is apparently needed indeed. I don't have a brilliant idea yet how to do it, but I'll leave the ticket open to remind the need.  Obviously ArrayIndexOutOfBoundsException should be avoided as well.

**Comment by martinpaljak** [comment]
My proposal would be to take mandatory tags from card data, taking into account that most cards today are valid GP 2.1.1 cards (vs OP2.0.1) and to support older cards without complaining with --relax. Suggestions for an informative error message are most welcome.

**Comment by 0xbaadf00d** [comment]
Hi, 

hmm ok, do you have a list of NFC Cards compatible with JavaCard application (.cap file) ?

**Comment by martinpaljak** [comment]
Any JavaCard card that has NFC interface or is dual-interface. Some quick samples: http://www.motechno.com/ibm-java-card-jcop.0.html?L= or http://www.smartcardfocus.com/shop/ilp/id~684/smartcafe-expert-6-0-80k-dual-/p/index.shtml Have a look at javacard buyer's guide for shop links

**Comment by 0xbaadf00d** [comment]
Thank you.

**Comment by martinpaljak** [comment]
As said, I'll leave this ticket open to fix two things:
- exception
- proper message for confirmed non-javacards

**Comment by martinpaljak** [comment]
Hopefully most of such bugs shall be removed after apdu4j gets the fuzzing terminal provider.

**Comment by dwimberger** [comment]
Maybe interpreting the card ATR could help (yes I know there are many unknowns, but hey, it's just an idea)?

```
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.HashMap;
import java.util.Locale;

/**
 * Class that implements ATR parsing to identify cards.
 * The card information is sourced from:
 * https://github.com/LudovicRousseau/pcsc-tools/blob/master/smartcard_list.txt
 * 
 * @author dwimberger@github
 * @license MIT 
 */
class CardDiagnosis {


	public static final String UNKNOWN = "UNKNOWN";
    public static final String SMARTCARDLIST_RESOURCE = "smartcard_list.txt";
    private static HashMap<String, String> c_CardList;

    private CardDiagnosis() {
    }//constructor

    public static String parseCardATR(String atr) {
        String _atr = atr.toUpperCase(Locale.ROOT);
        for(String entry:getCardList().keySet()) {
            if(_atr.matches(entry)) {
                return getCardList().get(entry);
            }
        }
        return UNKNOWN;
    }//parseCardATR

    private static HashMap<String, String> getCardList() {
        if (c_CardList == null) {
            HashMap<String, String> list = new HashMap<>();
            try (BufferedReader reader = new BufferedReader(
                    new InputStreamReader(
                        Thread.currentThread().getContextClassLoader().getResourceAsStream(SMARTCARDLIST_RESOURCE),
                        "utf-8"))) {
                boolean done = false;
                do {
                    String line = reader.readLine();
                    if (line == null) {
                        done = true;
                    } else if (line.startsWith("#") || line.matches("")) {
                        continue;
                    } else {
                        String atr = line.replace(" ", "").trim();
                        StringBuffer desc = new StringBuffer();
                        boolean descDone = false;
                        while(!descDone) {
                            String descLine = reader.readLine();
                            if(descLine == null) {
                                done = true;
                                break;
                            }
                            if (descLine.startsWith("\t")) {
                               desc.append((desc.length() > 0) ? ", " : "").append(descLine.trim());
                            } else {
                                descDone = true;
                                list.put(atr, desc.toString());
                            }
                        }
                    }
                } while (!done);
            } catch (IOException e) {
                e.printStackTrace();
            }
            c_CardList = list;
        }
        return c_CardList;
    }

    public static void main(String[] args) {
    	if(args != null && args.length == 1) {
    		System.out.println();
    		System.out.println(parseCardATR(args[0]));
    		System.out.println();
    	}
    }

}//class CardDiagnosis

```

**Comment by martinpaljak** [comment]
That is one option. But I'd like to avoid having anything related to ATR in GPPro code.

**Comment by martinpaljak** [comment]
@0xbaadf00d 
For the two options you specified, v0.4 will result in:
- Could not SELECT default selected: 0x6A80 (Wrong data/incorrect values in data)
- Could not SELECT Security Domain: 0x6A82 (Application/file not found)

Maybe this will be further improved with better exception handling in GPTool level.

@dwimberger There will be an "~~oracle~~Pythia" mode that will give you meaningful information about JavaCard-s (available from public sources), including keying information, so that first experiences would JustWork without any additional options. It will also make use of ATR during discovery stage, so yeah, probably it will give back information based on atr list as well, for cards that are not in the database.
