### ISSUE TITLE
Exception when installing CAP file

### ISSUE THREAD

**Issue by ibiglari** [martinpaljak/GlobalPlatformPro#44]
Hi.

I am getting this exception when trying to install my applets:

Exception in thread "main" java.lang.NullPointerException
        at java.io.FileInputStream.<init>(Unknown Source)
        at pro.javacard.gp.GPTool.main(GPTool.java:548)

That line doesn't look like it should be doing something very complicated. Does anybody have any idea why this exception is thrown?

Here's the DEBUG output of GP.exe:
````
[DEBUG] PlaintextKeys - static keys:
ENC: Ver:0 ID:0 Type:DES3 Len:16 Value:404142434445464748494A4B4C4D4E4F KCV: 8BAF47
MAC: Ver:0 ID:0 Type:DES3 Len:16 Value:404142434445464748494A4B4C4D4E4F KCV: 8BAF47
KEK: Ver:0 ID:0 Type:DES3 Len:16 Value:404142434445464748494A4B4C4D4E4F KCV: 8BAF47
# Detected readers from JNA2PCSC
[*] ACS ACR1281 1S Dual Reader PICC 0
SCardConnect("ACS ACR1281 1S Dual Reader PICC 0", T=*) -> T=1, 3B8B80010031C0641F27010000900036
SCardBeginTransaction("ACS ACR1281 1S Dual Reader PICC 0")
Reader: ACS ACR1281 1S Dual Reader PICC 0
ATR: 3B8B80010031C0641F27010000900036
More information about your card:
    http://smartcard-atr.appspot.com/parse?ATR=3B8B80010031C0641F27010000900036

A>> T=1 (4+0000) 00A40400 00
A<< (0063+2) (53ms) 6F3D8408A000000003000000A5319F6E2A4790516882310258006B223468000FA2000111422234426353624264536201FFFF0100000000000000009F6501FF 9000
[DEBUG] GlobalPlatform - Auto-detected ISD AID: A000000003000000
[WARN] GlobalPlatform - Unknown/unhandled tag in FCI proprietary data: 9F6E2A4790516882310258006B223468000FA2000111422234426353624264536201FFFF010000000000000000
[DEBUG] GlobalPlatform - Auto-detected block size: 255
***** Card info:
A>> T=1 (4+0000) 80CA9F7F 00
A<< (0045+2) (10ms) 9F7F2A4790516882310258006B223468000FA2000111422234426353624264536201FFFF010000000000000000 9000
Card CPLC:
ICFabricator: 4790
ICType: 5168
OperatingSystemID: 8231
OperatingSystemReleaseDate: 0258
OperatingSystemReleaseLevel: 006B
ICFabricationDate: 2234
ICSerialNumber: 68000FA2
ICBatchIdentifier: 0001
ICModuleFabricator: 1142
ICModulePackagingDate: 2234
ICCManufacturer: 4263
ICEmbeddingDate: 5362
ICPrePersonalizer: 4264
ICPrePersonalizationEquipmentDate: 5362
ICPrePersonalizationEquipmentID: 01FFFF01
ICPersonalizer: 0000
ICPersonalizationDate: 0000
ICPersonalizationEquipmentID: 00000000
***** CARD DATA
A>> T=1 (4+0000) 80CA0066 00
A<< (0051+2) (12ms) 6631732F06072A864886FC6B01600C060A2A864886FC6B02020101630906072A864886FC6B03640B06092A864886FC6B040215 9000
Unknown tag: 31
***** KEY INFO
A>> T=1 (4+0000) 80CA00E0 00
A<< (0020+2) (10ms) E012C00401018010C00402018010C00403018010 9000
VER:1 ID:1 TYPE:DES3 LEN:16
VER:1 ID:2 TYPE:DES3 LEN:16
VER:1 ID:3 TYPE:DES3 LEN:16
A>> T=1 (4+0008) 80500000 08 39692502711DFD1D 00
A<< (0028+2) (26ms) 03600000000168000FA2010200AD1089A9516A889330C7326E1DC7A6 9000
[DEBUG] GlobalPlatform - Host challenge: 39692502711DFD1D
[DEBUG] GlobalPlatform - Card challenge: 00AD1089A9516A88
[DEBUG] GlobalPlatform - Card reports SCP02 with version 1 keys
[DEBUG] PlaintextKeys - card keys:
ENC: Ver:0 ID:0 Type:DES3 Len:16 Value:6E715EDC24B47F23AAC4BCECCF24AD7B KCV: C8D607
MAC: Ver:0 ID:0 Type:DES3 Len:16 Value:C0D8C14C5E715E3FACFAC7FB0F38DCD4 KCV: 7F1182
KEK: Ver:0 ID:0 Type:DES3 Len:16 Value:C71CF7BAB2958FE622F47AC493357425 KCV: F36DE0
[DEBUG] PlaintextKeys - session keys:
ENC: Ver:0 ID:0 Type:DES3 Len:16 Value:5F27B52DF5E37F3FEC82C28630EF2C8E KCV: 9EF063
MAC: Ver:0 ID:0 Type:DES3 Len:16 Value:AF4A0D6043C7BD56D062222DF0D3BBB8 KCV: A29567
KEK: Ver:0 ID:0 Type:DES3 Len:16 Value:BB13E4C1DA859B10C410DCD7E8BD3667 KCV: 31673F
[DEBUG] GlobalPlatform - Verified card cryptogram: 9330C7326E1DC7A6
[DEBUG] GlobalPlatform - Calculated host cryptogram: CB3634416BC59C1F
A>> T=1 (4+0016) 84820100 10 CB3634416BC59C1F0DBF76ABE552AF10
A<< (0000+2) (28ms) 9000
CAP file (v2.1) generated on Sat Apr 16 11:31:09 EST 2016
By Sun Microsystems Inc. converter 1.3 with JDK 1.4.2_19 (Sun Microsystems Inc.)
Package: issuer v1.0 with AID 4B4650495353554552
Applet: Issuer with AID 4B465049535355455200
Import: 4B465042617365 v1.0
Import: A0000000620101 v1.2
Import: A0000000620001 v1.0
Total code size: 2042 bytes (2516 with debug)
SHA256 (code): 5CA3DAA3BAB25106C3166E187CA987BF720FF69F2E3B38FD585B6FC9B80C1C96
SHA1   (code): 8A9BD64F4A4030B4FA6BE3AB807D1BD7DF0CFE98
A>> T=1 (4+0010) 84F28002 0A 4F0075002CC6284E0B0D 00
A<< (0019+2) (16ms) E3114F08A0000000030000009F700107C5019E 9000
A>> T=1 (4+0010) 84F24002 0A 4F00F0BACCB5A4321908 00
A<< (0000+2) (14ms) 6A88
[WARN] GlobalPlatform - GET STATUS failed for 80F24002024F0000 with 6a88
A>> T=1 (4+0010) 84F22002 0A 4F00772E97E22624D343 00
A<< (0044+2) (24ms) E3144F07A00000000353509F700101C50100CE020203E3144F074B4650426173659F700101C50100CE020100 9000
A>> T=1 (4+0010) 84F21002 0A 4F0045C634FE9B2E1F67 00
A<< (0072+2) (28ms) E3304F07A00000000353509F700101C50100CE0202038407A00000000300008407A00000015100008408A000000003535041E3144F074B4650426173659F700101C50100CE020100 9000
A>> T=1 (4+0030) 84E60200 1E 094B465049535355455208A0000000030000000000005CE2BBE4E9CC8DA4
A<< (0001+2) (70ms) 00 9000
A>> T=1 (4+0255) 84E80000 FF C48207FA010013DECAFFED0102040001094B465049535355455202001F0013001F000E001F00C600500550002700F3000001D700020001001A03010004001F030001074B465042617365020107A0000000620101000107A000000062000103000E010A4B4650495353554552000009060050428004040004051300000359FFFFFFFFFFFFFFFFFFFFFFFF036F035D00740362037503B903D402B202C202D302E4034E810200800104141516170082000100010100000000800203000301010000041907055001035080050356002D02308F00123D8C001F3B7A0511188C001E181010900B8700181010910025870103301D10106D12AD019FD45F60A8FE5290
A<< (0001+2) (156ms) 00 9000
A>> T=1 (4+0255) 84E80001 FF 1D8F00253D8C00143759010170ED188F001C3D8C001D8702AD0303AD0392038D00203B188F00233D06058C00248704AD048B0026AD04AD0303058B0029188B002E7A80100201AE057502340004FFCA006DFFDC0155001100150020004D03311E10106D13AD001E2560081169868D001359020170ECAE0610106A081167008D00138D00151908AD000310108D00163B8D0017A801EC18078B0018AD041908058B00199901DC1063AD048B001A8D001B8D0013A801CCAE076166AE08750037000300010011000200200017002F18038809190304381804890AA801A618038809190305381804890AA8019718048B0018A8018F18048B001817E45583FC416B3B
A<< (0001+2) (67ms) 00 9000
A>> T=1 (4+0255) 84E80002 FF 18AD02830B7B0021AE0804432519037B0021AE08257B0021AE08044325438D0022890AA80164AE0704A3007418048B0018AE08AD01926C08116A868D001318AD01AE0824830C0319AD01AE0824830D830B0319AD01AE0824830E830B0319AD01AE0824830F031903AD01AE0824830F928D0022AD01AE0824830E830B928D0022AD01AE0824830D830B928D0022AD01AE0824830C928D0022890AA800ED116A868D0013A800E4AE079900D7AE08066D08116A868D0013AE0810176B1C18058B0018188B00276106188B0028AD041908058B0029A800B4AE0810186A08AE0810196B0A1810088B001870081810808B00188D0015AD02830B448A3881B2837EE9
A<< (0001+2) (57ms) 00 9000
A>> T=1 (4+0255) 84E80003 FF 7B0021AE08044325AD01AD10042524830E830B7B0021AE080443257B0021AE08257B0021AE08044325438D00163B1908AD01AD10042524830D830B7B0021AE080443257B0021AE08257B0021AE08044325438D00163BAD01AD10042524AE088B002A1908AD02830B7B0021AE080443257B0021AE08257B0021AE08044325438D00163B8D0017700A116A868D0013037804780110AD048B002B61081169828D00137A0210AD02830B103A25046B0504700303780320AD02830B7B002108251D418D002C78052105900B3D0303383D041D382D8D0015AD02830B7B0021101725AD01AD10042524830E830B7B0021101725058D00163B1A03D50C9478C6BFF14D
A<< (0001+2) (57ms) 00 9000
A>> T=1 (4+0255) 84E80004 FF AD01AD10042524830D830B7B0021101725058D00163BAD01AD1004252410188B002A1A03AD02830B7B0021101725058D00163B8D00177A0111188B002804782C03780130187701101007780530AD0003191E10108D0022780110111612780310AD110525730037000000040011001900200027002FAD1104108B387026AD11040438701FAD110408387018AD11041007387010AD1104100D3870081199008D00137A0310188B00276114AE076010119800AD02830B103A25418D00137A0510AD0303AD01AD10042524830F0310168D00163B7A0210188C002F18103D900B870B7A0310188C0030188F001C3D8C001D870E188F001C3D8CCDC54DAF2747F00E
A<< (0001+2) (57ms) 00 9000
A>> T=1 (4+0255) 84E80005 FF 001D870D1806900B870C7A04201D7301330003001900350041004D005900650071007C00870092009E00AA00B600C100CC00D600E000EA00F50100010B01160121012BAD0C033E2510805538A800F5AD0C033E2510405538A800E9AD0C033E2510205538A800DDAD0C033E2510105538A800D1AD0C033E2510085538A800C5AD0C033E25075538A800BAAD0C033E25055538A800AFAD0C033E25045538A800A4AD0C043E2510805538A80098AD0C043E2510405538A8008CAD0C043E2510205538A80080AD0C043E25101055387074AD0C043E25100855387069AD0C043E25075538705FAD0C043E250555387055AD0C043E2504553870BDBD8F6AA0C7A879
A<< (0001+2) (56ms) 00 9000
A>> T=1 (4+0255) 84E80006 FF 4BAD0C053E25108055387040AD0C053E25104055387035AD0C053E2510205538702AAD0C053E2510105538701FAD0C053E25100855387014AD0C053E25075538700AAD0C053E250555387A08002700020001000103001AFFFF00021618202223242526282A2B2C2D2E2F303135393A3B3C000000000500C600310200000002000001020000020280040E0200000302800402028004050280040302800404028004000280040602003A0002004402020044010200440002800200028004090280040D0100000006810701060003F80681080106811001068108020380040B03810901038109020681100501003A00060003EA0680040006410F1C0FD7B6B2E8
A<< (0001+2) (107ms) 00 9000
A>> T=1 (4+0255) 84E80007 FF 00001406811003050000000681100201810900068109000100440003810906030000140300001303810908030044010381090406811004018107000381030106820000068002000900F3009720080918020312020502101E1111140D0E04150807081302050A0609050B020C020304020302040203020402030502030602030206020302060203060E050B150B06170205050205020508060C0205020508060A020507020508061B10020F021E02080205020F0205020D020C02271315080707081707020C03020515110A063B0C0C0C0C0C0B0B0B0C0C0C0B0B0A0A0A0B0B0B0B0B0A0058070504080D0F040A040C05060709042F1103C854F17B2A601F63
A<< (0001+2) (547ms) 00 9000
A>> T=1 (4+0078) 84E88008 4E 0A0408080A03033D08080A0609100D350D0D0B0B130B0406081508030713080609110806090D0908060904080B081B071207110711070D090704071A4A071415080E040406042B53755EED3D9020
A<< (0001+2) (266ms) 00 9000
SCardEndTransaction()
SCardDisconnect("ACS ACR1281 1S Dual Reader PICC 0", true)
Exception in thread "main" java.lang.NullPointerException
        at java.io.FileInputStream.<init>(Unknown Source)
        at pro.javacard.gp.GPTool.main(GPTool.java:548)
```

**Comment by martinpaljak** [comment]
Please also give the version information (gp -V)

**Comment by ibiglari** [comment]
@martinpaljak Sorry it was a mistake on my part. I was using a batch file to load applet, which was created for an older version of `gp` and had both `--load` and `--install` in the command line. Something like this:

`gp --load applet.cap --install`

**Comment by dancvrcek** [comment]
just pottering around so wonder - should this cause an exception? Although don't know which version @ibiglari used.

**Comment by ibiglari** [comment]
@dancvrcek I downloaded the file yesterday. It's v0.3.9-0-g6f05e60

**Comment by martinpaljak** [comment]
Normally you should not get exceptions from the tool. That should be fixed.
Actually recent versions should be marked as experimental, i have not paid
that much attention to stability, rather feature exploration.
