### ISSUE TITLE
 Показан перевод для запроса много ошибок в установке, апплет не хочет быть Искать вместо этого перевод для много ошибок в установке, аплет не хочет быть many errors in the installation, the applet does not wish to be default

### ISSUE THREAD

**Issue by BushKape** [martinpaljak/GlobalPlatformPro#53]
installation with all the privileges:
`c:\work>gp --install online.cap --default --terminate -sdomain
[main] WARN pro.javacard.gp.GlobalPlatform - Unknown/unhandled tag in FCI propri
etary data: 9F6E06479100783300
Exception in thread "main" java.lang.IllegalArgumentException: apdu must be at l
east 4 bytes long
        at javax.smartcardio.CommandAPDU.parse(Unknown Source)
        at javax.smartcardio.CommandAPDU.<init>(Unknown Source)
        at pro.javacard.gp.GPTool.main(GPTool.java:468)
c:\work>gp -l
[main] WARN pro.javacard.gp.GlobalPlatform - Unknown/unhandled tag in FCI propri
etary data: 9F6E06479100783300
# Mode: GP211
ISD: A000000003000000 (OP_READY)
     Privs:   SecurityDomain, CardLock, CardTerminate, CVMManagement
PKG: A0000000035350 (LOADED)
     Applet:  A000000003535041`
Now let only default
`c:\work>gp --install online.cap --default
[main] WARN pro.javacard.gp.GlobalPlatform - Unknown/unhandled tag in FCI propri
etary data: 9F6E06479100783300
[main] WARN pro.javacard.gp.GlobalPlatform - GET STATUS failed for 80F24002024F0
000 with 6a88
CAP loaded
[main] WARN pro.javacard.gp.GlobalPlatform - GET STATUS failed for 80F24002024F0
000 with 6a88

c:\work>gp -l
[main] WARN pro.javacard.gp.GlobalPlatform - Unknown/unhandled tag in FCI propri
etary data: 9F6E06479100783300
# Mode: GP211
ISD: A000000003000000 (OP_READY)
     Privs:   SecurityDomain, CardLock, CardTerminate, CVMManagement

APP: D1D2D3D4D50101 (SELECTABLE)
     Privs:   CardReset

PKG: A0000000035350 (LOADED)
     Applet:  A000000003535041

PKG: D1D2D3D4D501 (LOADED)
     Applet:  D1D2D3D4D50101
`
Now terminate 
`c:\work>gp --install online.cap --default --terminate
[main] WARN pro.javacard.gp.GlobalPlatform - Unknown/unhandled tag in FCI propri
etary data: 9F6E06479100783300
[main] WARN pro.javacard.gp.GlobalPlatform - GET STATUS failed for 80F24002024F0
000 with 6a88
CAP loaded
[main] WARN pro.javacard.gp.GlobalPlatform - GET STATUS failed for 80F24002024F0
000 with 6a88

c:\work>gp -l
[main] WARN pro.javacard.gp.GlobalPlatform - Unknown/unhandled tag in FCI propri
etary data: 9F6E06479100783300
# Mode: GP211
ISD: A000000003000000 (OP_READY)
     Privs:   SecurityDomain, CardLock, CardTerminate, CVMManagement

APP: D1D2D3D4D50101 (SELECTABLE)
     Privs:   CardLock, CardTerminate, CardReset

PKG: A0000000035350 (LOADED)
     Applet:  A000000003535041

PKG: D1D2D3D4D501 (LOADED)
     Applet:  D1D2D3D4D50101
`
how to avoid these mistakes and make the applet defaults?

**Comment by BushKape** [comment]
[DEBUG] PlaintextKeys - static keys:
ENC: Ver:0 ID:0 Type:DES3 Len:16 Value:404142434445464748494A4B4C4D4E4F KCV: 8BA
F47
MAC: Ver:0 ID:0 Type:DES3 Len:16 Value:404142434445464748494A4B4C4D4E4F KCV: 8BA
F47
KEK: Ver:0 ID:0 Type:DES3 Len:16 Value:404142434445464748494A4B4C4D4E4F KCV: 8BA
F47
Reader: ACS CCID USB Reader 0
ATR: 3BF81300008131FE454A434F5076323431B7
More information about your card:
    http://smartcard-atr.appspot.com/parse?ATR=3BF81300008131FE454A434F507632343
1B7

[DEBUG] GlobalPlatform - Auto-detected ISD AID: A000000003000000
[DEBUG] GlobalPlatform - Auto-detected block size: 255
[WARN] GlobalPlatform - Unknown/unhandled tag in FCI proprietary data: 9F6E06479
100783300
[DEBUG] GlobalPlatform - Auto-detected GP version: GP211
[DEBUG] GlobalPlatform - Host challenge: DB44B443FF8A5F5A
[DEBUG] GlobalPlatform - Card challenge: 008C4A551E5ACEDB
[DEBUG] GlobalPlatform - Card reports SCP02 with version 255 keys
[DEBUG] PlaintextKeys - session keys:
ENC: Ver:0 ID:0 Type:DES3 Len:16 Value:62883AD9B4DDCAEE065F43297BF6B94F KCV: D48
B86
MAC: Ver:0 ID:0 Type:DES3 Len:16 Value:EB48FC532917664D93F26DABC713CEFA KCV: A36
116
KEK: Ver:0 ID:0 Type:DES3 Len:16 Value:B44BE2857160E662FA389C746A8EE675 KCV: AC8
6B2
[DEBUG] GlobalPlatform - Verified card cryptogram: 7FFE14AC7F4E2697
[DEBUG] GlobalPlatform - Calculated host cryptogram: F43F6848FCF2E00B
CAP file (v2.1) generated on Sat May 21 00:04:02 MSK 2016
By Sun Microsystems Inc. converter 1.3 with JDK 1.8.0_74 (Oracle Corporation)
Package: online v1.0 with AID D1D2D3D4D501
Applet: online with AID D1D2D3D4D50101
Import: A0000000620101 v1.3
Import: A0000000620001 v1.0
Total code size: 1062 bytes (1328 with debug)
SHA256 (code): AD23782733D7D69A44A3527ACD1661AE0231EBB621FBC0C1434006050653329E
SHA1   (code): FAC1A4CE3FBCCBE28B42AAA9D08F2663F62A8274
[WARN] GlobalPlatform - GET STATUS failed for 80F24002024F0000 with 6a88
CAP loaded
[WARN] GlobalPlatform - GET STATUS failed for 80F24002024F0000 with 6a88

**Comment by martinpaljak** [comment]
1) The (now deprecated) -sdomain option can not be used with applets.
2) I'll check if the installation works as expected.
