### ISSUE TITLE
Bug with host cryptogram calculation in SCP02

### ISSUE THREAD

**Issue by minkyn** [martinpaljak/GlobalPlatformPro#56]
I have my custom keyset of ENC, MAC, KEK running under SCP02:
```
gp -d -v --scp 2 --key-enc XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX --key-mac YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY --key-kek ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ --list
```

I got the command output:
```
GlobalPlatformPro v0.3.9-24-g7e62155
Running on Mac OS X 10.12.1 x86_64, Java 1.8.0_60 by Oracle Corporation
Unlimited crypto policy is NOT installed!
ATTENTION: Overriding default keys ...
[DEBUG] PlaintextKeys - static keys: 
ENC: Ver:0 ID:0 Type:DES3 Len:16 Value:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX KCV: D3A661
MAC: Ver:0 ID:0 Type:DES3 Len:16 Value:YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY KCV: AEE3F5
KEK: Ver:0 ID:0 Type:DES3 Len:16 Value:ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ KCV: FC6828
# Detected readers from JNA2PCSC
[*] ACS ACR 38U-CCID
SCardConnect("ACS ACR 38U-CCID", T=*) -> T=0, 3B9F95801FC78031E073FE2113671192004001000118
SCardBeginTransaction("ACS ACR 38U-CCID")
Reader: ACS ACR 38U-CCID
ATR: 3B9F95801FC78031E073FE2113671192004001000118
More information about your card:
    http://smartcard-atr.appspot.com/parse?ATR=3B9F95801FC78031E073FE2113671192004001000118

A>> T=0 (4+0000) 00A40400 00 
A<< (0017+2) (17ms) 6F0F8407A0000001510000A5049F6501FF 9000
[DEBUG] GlobalPlatform - Auto-detected ISD AID: A0000001510000
[DEBUG] GlobalPlatform - Auto-detected block size: 255
A>> T=0 (4+0008) 80500000 08 2E07ADE6502DC607 00
A<< (0028+2) (15ms) 0000C6D86A1CB20214132002000DFBC91D4F0C9E68060E82EA5C814B 9000
[DEBUG] GlobalPlatform - Host challenge: 2E07ADE6502DC607
[DEBUG] GlobalPlatform - Card challenge: 000DFBC91D4F0C9E
[DEBUG] GlobalPlatform - Card reports SCP02 with version 32 keys
[DEBUG] PlaintextKeys - session keys: 
ENC: Ver:0 ID:0 Type:DES3 Len:16 Value:AD24EAD378F1365E333FCBE909F3E6D2 KCV: 99BDEA
MAC: Ver:0 ID:0 Type:DES3 Len:16 Value:DCB288C75E7B4970E840FCB56A139507 KCV: 24138C
KEK: Ver:0 ID:0 Type:DES3 Len:16 Value:9E0E9B5D4B76B102ED0FCB6A1E3F0166 KCV: 4B590A
[DEBUG] GlobalPlatform - Verified card cryptogram: 68060E82EA5C814B
[DEBUG] GlobalPlatform - Calculated host cryptogram: 9C650864521157D8
A>> T=0 (4+0016) 84820100 10 9C650864521157D8126595F7B75ABC18
A<< (0000+2) (8ms) 6982
pro.javacard.gp.GPException: External authenticate failed SW: 6982
	at pro.javacard.gp.GPException.check(GPException.java:66)
	at pro.javacard.gp.GlobalPlatform.openSecureChannel(GlobalPlatform.java:602)
	at pro.javacard.gp.GPTool.main(GPTool.java:465)
External authenticate failed SW: 6982
```

I ran with other tools (e.g. GPShell) and there is nothing wrong with the external authentication. I'm 100% sure of the correctness of my keyset, because when I manually changed that, I would get:
```
!!! DO NOT RE-TRY THE SAME COMMAND/KEYS OR YOU MAY BRICK YOUR CARD !!!
	at pro.javacard.gp.GlobalPlatform.giveStrictWarning(GlobalPlatform.java:207)
	at pro.javacard.gp.GlobalPlatform.openSecureChannel(GlobalPlatform.java:583)
	at pro.javacard.gp.GPTool.main(GPTool.java:465)
STRICT WARNING: Card cryptogram invalid!
```

Can you double check the host cryptogram logic please?

**Comment by minkyn** [comment]
I think I identified where the bug is. In `GlobalPlatform.wrap(CommandAPDU)` method, the way to compute MAC for SCP02 is:

1. Use key-mac to DES-CBC encrypt [old_CLA, old_INS, old_P1, old_P2, old_Lc, old_Data[:3]] with ICV being all zeros, and get the result as new_ICV;
2. Use key-mac to 3DES-CBC old_data[3:] in pad80 with new_ICV, and get the result as MAC (8 bytes).

Your current implementation isn't doing that.

**Comment by martinpaljak** [comment]
The implementation has been used with several cards without issues.

Which card are you using? Anyway, will investigate ASAP.

**Comment by minkyn** [comment]
Looks like it's the card that has transient errors. It is working now ....
