### ISSUE TITLE
Unable to initiate a scp03 session?

### ISSUE THREAD

**Issue by totszwai** [martinpaljak/GlobalPlatformPro#62]
Hi,

I'm trying to run this basic command against a blank Oberthur ID-One v8 card, and it seems not able to establish SCP03 session? I am also new into the whole smartcard thing, so if I'm running the commands wrong, please let me know.

```
gp -l -d -v
[DEBUG] PlaintextKeys - static keys:
ENC: Ver:0 ID:0 Type:DES3 Len:16 Value:404142434445464748494A4B4C4D4E4F KCV: 8BAF47
MAC: Ver:0 ID:0 Type:DES3 Len:16 Value:404142434445464748494A4B4C4D4E4F KCV: 8BAF47
KEK: Ver:0 ID:0 Type:DES3 Len:16 Value:404142434445464748494A4B4C4D4E4F KCV: 8BAF47
# Detected readers from JNA2PCSC
[*] ACS ACR39U ICC Reader 0
SCardConnect("ACS ACR39U ICC Reader 0", T=*) -> T=1, 3BD6970081B1FE451F078031C1521118F9
SCardBeginTransaction("ACS ACR39U ICC Reader 0")
Reader: ACS ACR39U ICC Reader 0
ATR: 3BD6970081B1FE451F078031C1521118F9
More information about your card:
    http://smartcard-atr.appspot.com/parse?ATR=3BD6970081B1FE451F078031C1521118F9

A>> T=1 (4+0000) 00A40400 00
A<< (0066+2) (58ms) 6F408407A0000001510000A535732F06072A864886FC6B01600C060A2A864886FC6B02020201630906072A864886FC6B03640B06092A864886FC6B0403709F6501FF 9000
[DEBUG] GlobalPlatform - Auto-detected ISD AID: A0000001510000
[DEBUG] GlobalPlatform - Auto-detected GP version: GP22
[DEBUG] GlobalPlatform - Auto-detected block size: 255
A>> T=1 (4+0008) 80500000 08 6F0CD0DB2C6462C5 00
A<< (0032+2) (304s266ms) 1424613300001AA00100010370C2247885FB5321D4EC35A1EC595494E7000011 9000
[DEBUG] GlobalPlatform - Host challenge: 6F0CD0DB2C6462C5
[DEBUG] GlobalPlatform - Card challenge: C2247885FB5321D4
[DEBUG] GlobalPlatform - Card reports SCP03 with version 1 keys
[DEBUG] GlobalPlatform - SCP03 i=112
[DEBUG] PlaintextKeys - session keys:
ENC: Ver:0 ID:0 Type:AES Len:16 Value:B5945860AE54730EF6D1869040E0547C KCV: 85D2A0
MAC: Ver:0 ID:0 Type:AES Len:16 Value:7B71175F90F8729A03B2D06566A54D5D KCV: 03AFF7
KEK: Ver:0 ID:0 Type:DES3 Len:16 Value:404142434445464748494A4B4C4D4E4F KCV: 8BAF47
pro.javacard.gp.GPException: STRICT WARNING: Card cryptogram invalid!
Card: EC35A1EC595494E7
Host: 2AA4AF9689B10560
!!! DO NOT RE-TRY THE SAME COMMAND/KEYS OR YOU MAY BRICK YOUR CARD !!!
        at pro.javacard.gp.GlobalPlatform.giveStrictWarning(GlobalPlatform.java:207)
        at pro.javacard.gp.GlobalPlatform.openSecureChannel(GlobalPlatform.java:583)
        at pro.javacard.gp.GPTool.main(GPTool.java:463)
```

**Comment by martinpaljak** [comment]
You need to know the gp keys.

**Comment by martinpaljak** [comment]
You really need to know the keys of the card. There will be a longer and more detailed introduction in the README of next version, with more options and hopefully more success on first use, but until that time you need to know the keys.
