### ISSUE TITLE
Install for Install and make selectable failed SW: 6985 - when installing OpenPGPApplet to JavaCOS A22

### ISSUE THREAD

**Issue by siigna** [martinpaljak/GlobalPlatformPro#74]
```
λ gp -V
GlobalPlatformPro v0.3.9-0-g6f05e60
Running on Windows 10 10.0 amd64, Java 1.8.0_131 by Oracle Corporation
```
```
λ gp -l
[main] WARN pro.javacard.gp.GlobalPlatform - GET STATUS failed for 80F24002024F0000 with 6a88
[main] WARN pro.javacard.gp.GlobalPlatform - GET STATUS failed for 80F22002024F0000 with 6a88
[main] WARN pro.javacard.gp.GlobalPlatform - GET STATUS failed for 80F21002024F0000 with 6a88
# Mode: GP211
ISD: A000000003000000 (OP_READY)
     Privs:   SecurityDomain, CardLock, CardTerminate, CardReset, CVMManagement
```
```
λ gp -install ..\src\AppletPlayground\OpenPGPApplet.cap
[main] WARN pro.javacard.gp.GlobalPlatform - GET STATUS failed for 80F24002024F0000 with 6a88
[main] WARN pro.javacard.gp.GlobalPlatform - GET STATUS failed for 80F22002024F0000 with 6a88
[main] WARN pro.javacard.gp.GlobalPlatform - GET STATUS failed for 80F21002024F0000 with 6a88
CAP loaded
[main] WARN pro.javacard.gp.GlobalPlatform - GET STATUS failed for 80F24002024F0000 with 6a88
pro.javacard.gp.GPException: Install for Install and make selectable failed SW: 6985
        at pro.javacard.gp.GPException.check(GPException.java:66)
        at pro.javacard.gp.GlobalPlatform.installAndMakeSelectable(GlobalPlatform.java:746)
        at pro.javacard.gp.GPTool.main(GPTool.java:592)
```
([Debug install output here...](https://github.com/martinpaljak/GlobalPlatformPro/files/1195733/gp_install_debug.txt))
```
λ gp -l
[main] WARN pro.javacard.gp.GlobalPlatform - GET STATUS failed for 80F24002024F0000 with 6a88
# Mode: GP211
ISD: A000000003000000 (OP_READY)
     Privs:   SecurityDomain, CardLock, CardTerminate, CardReset, CVMManagement

PKG: D27600012401 (LOADED)
     Version: 0.0
     Applet:  D2760001240102000000DEADBEEF0000
```

**Comment by martinpaljak** [comment]
1. The warnings (as the name implies) should be harmless and indicate no support from the card for that data group for a clean card (with just the ISD). You can ignore them or suggest some better handling so that they would not scare users.
2. As the application loads (you get the package on the card) thus it should be the right JC target, but as you get 6985 on install, I guess indicates that the installation of the applet did not succeed for some reason. Check the install method for initialisations that do not match the card specification (or maybe the applet throws it during install itself, I do not know). If you remove most of the initialization from the install() and applet construction, check if it loads, and add back one by one the uncommented lines to find out what exactly is causing the problem

**Comment by siigna** [comment]
I ended up trying the [OpenPGPApplet cap from JavaCard OS](https://javacardos.com/javacardforum/viewtopic.php?f=36&t=25#p1724).  It installed successfully.
```
λ gp -install openpgpcard-v1.1-JC222.cap
[main] WARN pro.javacard.gp.GlobalPlatform - GET STATUS failed for 80F24002024F0000 with 6a88
[main] WARN pro.javacard.gp.GlobalPlatform - GET STATUS failed for 80F22002024F0000 with 6a88
[main] WARN pro.javacard.gp.GlobalPlatform - GET STATUS failed for 80F21002024F0000 with 6a88
CAP loaded
[main] WARN pro.javacard.gp.GlobalPlatform - GET STATUS failed for 80F24002024F0000 with 6a88
```
([Debug install output here...](https://github.com/martinpaljak/GlobalPlatformPro/files/1198582/gp_install_debug.txt))
```
λ gp -l
# Mode: GP211
ISD: A000000003000000 (OP_READY)
     Privs:   SecurityDomain, CardLock, CardTerminate, CardReset, CVMManagement

APP: D2760001240102000000000000010000 (SELECTABLE)

PKG: D27600012401 (LOADED)
     Version: 1.0
     Applet:  D2760001240102000000000000010000
```
```
λ gpg --card-status
gpg: NOTE: THIS IS A DEVELOPMENT VERSION!
gpg: It is only intended for test purposes and should NOT be
gpg: used in a production environment or with production keys!
Reader ...........: SCM Microsystems Inc. SCRx31 USB Smart Card Reader 0
Application ID ...: D2760001240102000000000000010000
Version ..........: 2.0
Manufacturer .....: test card
Serial number ....: 00000001
Name of cardholder: [not set]
Language prefs ...: [not set]
Sex ..............: unspecified
URL of public key : [not set]
Login data .......: [not set]
Signature PIN ....: forced
Key attributes ...: rsa2048 rsa2048 rsa2048
Max. PIN lengths .: 127 127 127
PIN retry counter : 3 3 3
Signature counter : 0
Signature key ....: [none]
Encryption key....: [none]
Authentication key: [none]
General key info..: [none]
```

**Comment by ReekyMarko** [comment]
I'm having the same error here with the same card. @siigna can you please tell me where you got the prebuilt cap file?

**Comment by martinpaljak** [comment]
Do open a new ticket with full log etc, if relevant
