### ISSUE TITLE
GET STATUS FAILED when upgrading from v0.3.7 to v0.3.9

### ISSUE THREAD

**Issue by thotheolh** [martinpaljak/GlobalPlatformPro#80]
I don't usually see the GET STATUS failed when I am using v0.3.7 and older versions but when I upgraded to v0.3.9, it has the error messages.

**Comment by tsenger** [comment]
Same here with G&D Sm@rtCafé card. Using v0.3.7 result seems okay:
```
java -jar gp.jar -ld
# Detected readers from JNA2PCSC
[ ] PersoSimHandshake 00 00
[*] SCL010 Contactless Reader [SCL010 Contactless Reader] (00000741000005) 00 00
SCardConnect("SCL010 Contactless Reader [SCL010 Contactless Reader] (00000741000005) 00 00", T=*) -> T=1, 3B8980015343453720000020204A
SCardBeginTransaction("SCL010 Contactless Reader [SCL010 Contactless Reader] (00000741000005) 00 00")
A>> T=1 (4+0000) 00A40400 00 
A<< (0018+2) (111ms) 6F108408A000000003000000A5049F6501FF 9000
A>> T=1 (4+0008) 80500000 08 18065633407B17A5 00
A<< (0028+2) (68ms) 0000054F002A0044AB010102001B9B95B95E5EBCABB137C7B87EE6EF 9000
A>> T=1 (4+0016) 84820100 10 9D300822A9ACF7059A8CACFE450C2A0F
A<< (0000+2) (42ms) 9000
A>> T=1 (4+0010) 84F28000 0A 4F008B28B60A425106E6 00
A<< (0011+2) (33ms) 08A0000000030000000F9E 9000
A>> T=1 (4+0010) 84F24000 0A 4F005F7B7E4608361142 00
A<< (0000+2) (31ms) 6A88
A>> T=1 (4+0010) 84F22000 0A 4F00657AFEB0CBB87F40 00
A<< (0010+2) (33ms) 07A00000015153500100 9000
A>> T=1 (4+0010) 84F21000 0A 4F008657307F71225724 00
A<< (0000+2) (28ms) 6A86
AID: A000000003000000 (|........|)
     ISD SECURED: Security Domain, Card lock, Card terminate, Default selected, CVM (PIN) management

AID: A0000001515350 (|....QSP|)
     Exe LOADED: (none)

SCardEndTransaction()
SCardDisconnect("SCL010 Contactless Reader [SCL010 Contactless Reader] (00000741000005) 00 00", true)
```

Same card with v0.3.9 results in:
```
java -jar gp.jar -ld 
# Detected readers from JNA2PCSC
[ ] PersoSimHandshake 00 00
[*] SCL010 Contactless Reader [SCL010 Contactless Reader] (00000741000005) 00 00
SCardConnect("SCL010 Contactless Reader [SCL010 Contactless Reader] (00000741000005) 00 00", T=*) -> T=1, 3B8980015343453720000020204A
SCardBeginTransaction("SCL010 Contactless Reader [SCL010 Contactless Reader] (00000741000005) 00 00")
A>> T=1 (4+0000) 00A40400 00 
A<< (0018+2) (127ms) 6F108408A000000003000000A5049F6501FF 9000
A>> T=1 (4+0008) 80500000 08 2B45E5DCB37A3025 00
A<< (0028+2) (69ms) 0000054F002A0044AB010102001C389736801E914603CEAF9242C6F2 9000
A>> T=1 (4+0016) 84820100 10 DE7D78A7DA5993910C7B874A36864E4E
A<< (0000+2) (27ms) 9000
A>> T=1 (4+0010) 84F28002 0A 4F0067CFDBFE88DEB51B 00
A<< (0072+2) (44ms) E3464F08A0000000030000009F70010FC5039EFE80CF0140CF0141CF0142CF0143CF0180CF0181CF0182CF0183C40BD276000005AAFFCAFE0001CE020001CC08A000000003000000 9000
SCardEndTransaction()
SCardDisconnect("SCL010 Contactless Reader [SCL010 Contactless Reader] (00000741000005) 00 00", true)
Exception in thread "main" java.lang.IllegalArgumentException: AID's are between 5 and 16 bytes, not 1
	at pro.javacard.gp.AID.<init>(AID.java:67)
	at pro.javacard.gp.AID.<init>(AID.java:43)
	at pro.javacard.gp.GPRegistry.populate_tags(GPRegistry.java:234)
	at pro.javacard.gp.GPRegistry.parse(GPRegistry.java:288)
	at pro.javacard.gp.GlobalPlatform.getStatus(GlobalPlatform.java:1051)
	at pro.javacard.gp.GlobalPlatform.getRegistry(GlobalPlatform.java:983)
	at pro.javacard.gp.GPTool.main(GPTool.java:685)
```

**Comment by martinpaljak** [comment]
Dup of #83
